### ISSUE TITLE
bilibili网页端添加APP首页推荐无效

### ISSUE THREAD

**Issue by neking2003** [indefined/UserScripts#10]
firefox 69.0
tampermonkey 4.9.5941
网页端无法看到首页推荐

**Comment by indefined** [comment]
我这边相同的配置测试并没有问题。
脚本只会在网页端首页生效，目前仅包括https://www.bilibili.com/ 和 https://www.bilibili.com/index.html 两个链接，如果有其它的首页地址的话我会包括进去。
另外近日B站首页有在改版，但是仅有部分用户收到灰度测试，我这边的浏览器和账户都没接到测试仍然是旧版状态的所以也没办法进行兼容，相关情况我会留意一下的如果有更新会及时跟进，如果有新情报也请继续反馈

**Comment by indefined** [comment]
如果仍旧是旧版请按F12或者ctrl+shift+k查看控制台是否有错误输出

**Comment by neking2003** [comment]
这是控制台的内容，有8个警告，不知道有没有关系


在 2019-09-15 14:06:31，"indefined" <notifications@github.com> 写道：


如果仍旧是旧版请按F12或者ctrl+shift+k查看控制台是否有错误输出

**Comment by neking2003** [comment]
//
         \\         //
          \\       //
    ##DDDDDDDDDDDDDDDDDDDDDD##
    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___
    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \
    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \
    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \
    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \
    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\
    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|
    ## MMMMMMMMMMMMMMMMMMMM ##
    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 2.6.1. Powered by jinkela-core 2.4.12.
         \/            \/ home.20417b5bad6620f1709a36acc47fa11a7eb81053.js:1:4661
即使其 MIME 类型（“application/json”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://api.bilibili.com/x/web-interface/nav?callback=jqueryCallback_bili_5695621968216192&jsonp=jsonp&_=1568738323742”的脚本。
www.bilibili.com
即使其 MIME 类型（“application/json”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://api.bilibili.com/x/web-show/res/locs?callback=jquery…2870%2C2953%2C2954%2C2955%2C2956&jsonp=jsonp&_=1568738323745”的脚本。
www.bilibili.com
即使其 MIME 类型（“application/json”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://api.bilibili.com/x/web-interface/index/icon?callback…ryCallback_bili_9451234291749523&jsonp=jsonp&_=1568738323743”的脚本。
www.bilibili.com
即使其 MIME 类型（“application/json”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://api.bilibili.com/x/web-interface/online?callback=jqu…yCallback_bili_24761683358113684&jsonp=jsonp&_=1568738323744”的脚本。
www.bilibili.com
即使其 MIME 类型（“application/json”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://api.bilibili.com/x/web-show/res/locs?callback=jquery…68%2C1636%2C1570%2C1572%2C1574%2C2207%2C2257&_=1568738323746”的脚本。
www.bilibili.com
即使其 MIME 类型（“application/json”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://api.bilibili.com/x/member/security/status?callback=j…22224-CBB8-46BB-8DF2-DB59B763C69D110265infoc&_=1568738323747”的脚本。
www.bilibili.com

​图片粘不了，就复制文本到这里吧，6个警告

**Comment by indefined** [comment]
警告应该是无关的，如果是脚本执行错误应该会有红色感叹号的错误
新更新了提取疑似新版cookie的一个小版本，如果能看到`添加APP首页推荐找不到动画版块`相关的错误提示的话请反馈后面显示的字符串（已去除个人信息），不过看你这情况应该也是看不到提示的，如果没有错误就无从判断了……

**Comment by neking2003** [comment]
大佬，我知道问题出在哪了
你的插件写的适用网站是：
// @match *://www.bilibili.com/
// @match *://www.bilibili.com/index.html
但是我的B站自动登录的网页地址是：
https://www.bilibili.com/?1458726513345
所以我加了一句
// @match *://www.bilibili.com/*
就可以看到猜你喜欢了

在 2019-09-18 20:08:28，"indefined" <notifications@github.com> 写道：


警告应该是无关的，如果是脚本执行错误应该会有红色感叹号的错误
新更新了提取疑似新版cookie的一个小版本，如果能看到添加APP首页推荐找不到动画版块相关的错误提示的话请反馈后面显示的字符串（已去除个人信息），不过看你这情况应该也是看不到提示的，如果没有错误就无从判断了……

**Comment by indefined** [comment]
嗯……我倒是没想到，其实这种可能性在#8 中有提过，但是我想出这种意外情况就没添加进去。顺便你这个网址如果不是自己保存而是自动跳转的那可能是被恶意插件什么塞的推广后缀

网址已改为全局通配，这个issue就暂时先开着吧，留着看有没有人反馈新版适配问题，如果怕打扰到的话可以点issue右侧的`Unsubscribe`按钮取消订阅

**Comment by aoxu** [comment]
我遇到了新版适配问题，首页确实能看到动画模块，console红色错误提示如下
```
添加APP首页推荐找不到动画版块，反馈请提供下面cookie字符串（已去除个人信息） fts=1510069952; uTZ=-480; im_notify_type_******=0; LIVE_BUVID=********************************; LIVE_BUVID__ckMd5=****************; PHPSESSID=****************r1t1mqgaa0; CURRENT_QUALITY=80; CURRENT_FNVAL=16; sid=8cevjpa3; _uuid=B0F32A85-D702-4C52-4D6B-****************8infoc; stardustvideo=1; stardustpgcv=0606; im_local_unread_******=0; im_seqno_******=1; from=pc; buvid3=14D61A82-E6E2-45D2-8225-****************3infoc; rpdid=|(um|JR~JY|l0J'ullYu|k|)R; UM_distinctid=16d536c119e2c8-003da94ad17fe7-67e1b3f-1fa400-16d536c119f77a; DedeUserID=******; DedeUserID__ckMd5=****************; bili_jct=********************************; _uuid=CA865782-1DBE-945C-3A73-****************6infoc; bp_t_offset_******=****************34; finger=b3372c5f; INTVER=1
eval @ chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=4b998d7d-9779-4a5a-9995-3ce6381137ae:742
```

**Comment by indefined** [comment]
> 我遇到了新版适配问题，首页确实能看到动画模块，console红色错误提示如下
> 
感谢反馈，需要一些时间进行适配。看上去好像开个新话题讨论比较方便的样子，毕竟不知道后面还会不会改，这个话题就关了吧
