### ISSUE TITLE
[HTML5视频截图器]请求允许下载格式可切换为png

### ISSUE THREAD

**Issue by MY1L** [indefined/UserScripts#100]
该脚本非常好使，解决了跳到b站港澳台就不能开启[the1812/Bilibili-Evolved](https://github.com/the1812/Bilibili-Evolved)脚本的难题。
您可能也在用Bilibili-Evolved，其截屏功能允许批量截屏并打包下载，且可以设置保存为png。
我的请求如题，因为目前用该脚本对动画逐帧检查要挨个右键“下载.png”非常不便……当然，如果能考虑模仿Bilibili-Evolved的批量截屏就更好了。

**Comment by indefined** [comment]
保存为png以及批量下载的功能倒是不难做，问题在实现的逻辑，这个脚本按钮和按键已经很多了，多增加一个下载png的按键显然很多余，而增加一个批量下载我都不知道要放在哪里以及怎么放。这个脚本本来只是打算做个简单的截图下载，但现在功能按钮和设置已经十分复杂了，可以说大多数按钮和设置已经超出了大多数人的需求，但脚本本身功能却并不多而且有很大的先天缺陷。保存png大概我可以在设置里增加一个选项，至于批量下载……我再考虑一下怎么做吧

**Comment by MY1L** [comment]
噢，并不是要新增一个下载png的按键，而是希望有个配置功能调整下载按钮（我应该用不到下jpg这功能了），比如放在修改快捷键那里。
同时时间戳的格式可能也需要一个配置。目前文件名格式可能影响md的插图。

我刚才比较急用所以先改了脚本
 ```
236行        const name = `${document.title}_${timestamp}.png`;
246行            },'image/png');
```
指望强行将下载换成png，结果发现下载的截屏变成32位带α透明的png了，不清楚为什么（这个问题不大，只是png体积臃肿了点，需要我再处理）

Bilibili-Evolved那种批量下载倒无需配置，它只是在点截屏按钮时将预览图甩到右上角，在截第2张屏时才出现打包下载/删除按钮，和该脚本新建页面放图的流程不同。这个功能倒不急。

**Comment by indefined** [comment]
先增加了一个下载png的设置，时间戳换成了下划线代替分秒符

**Comment by indefined** [comment]
把evo的截图暂存面板模样抄过来了，虽然代码没有结构化越来越乱了但功能应该正常能用，现在截图按钮不会直接弹出新窗口而是悬浮在右侧面板上可以选择批量下载

**Comment by MY1L** [comment]
我要试试~
题外话，截屏下载为带α透明的png（但截屏实际上不透明）是canvas存图自身的特性，所以无解吗？

**Comment by indefined** [comment]
应该是没法去除的，我查了一下是可以关掉画布的α通道，但实际导出为png还是会带α通道
