### ISSUE TITLE
[HTML5截图] 全屏尝试覆盖快捷键问题

### ISSUE THREAD

**Issue by KANA108** [indefined/UserScripts#101]
脚本在网页全屏的情况下无法点击到“尝试覆盖网页快捷键”。

**Comment by indefined** [comment]
请说明什么网站以及详细说明你想干什么。如果我没猜错你应该说的是截图的脚本，很多问题脚本说明里已经写了，尝试覆盖快捷键并不一定能保证覆盖成功，目前也没有针对性适配的打算，很多就是想解决也解决不了。或者你是想说全屏无法打开工具栏，那也很正常，因为视频全屏比工具栏高度高所以你点不到
