### ISSUE TITLE
[网易CC直播净化] 脚本失效了

### ISSUE THREAD

**Issue by lelouch1021** [indefined/UserScripts#102]
1. 脚本名称：网易CC直播净化

2. 脚本使用环境：win10 chrome(102.0.5005.115) Tampermonkey BETA(4.18.6165) 

3. 问题详细描述：脚本失效了

![)_B{}8B@}U8AMIXHA$(7OY2](https://user-images.githubusercontent.com/23654806/174292783-ee05cd04-d30f-4936-86f0-c2861c829a45.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
已更新，未全面测试，如果有别的问题或者哪个直播间不生效在下面回复
