### ISSUE TITLE
[Bilibili直播间工具] 升级下级所需亲密度显示错误

### ISSUE THREAD

**Issue by URGERKING** [indefined/UserScripts#103]
1. 脚本名称：bilibili直播间工具0.5.47.3

2. 脚本使用环境：Windows 7 64-bit (WoW64)   OperaGx LVL3 (core: 87.0.4390.58)/Firefox 99.0.1 (20220411174855) Tampermonkey v4.16.6160

3. 问题详细描述：升至下级所需亲密度显示错误(航海亲密度不清楚)

![image](https://user-images.githubusercontent.com/63456882/174507983-98d04ebe-be31-4f6a-906e-083f2b4dec15.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
每次都一样吗？我看了一下我的勋章列表没有发现问题，接口定义似乎也没有更改

**Comment by URGERKING** [comment]
> 每次都一样吗？我看了一下我的勋章列表没有发现问题，接口定义似乎也没有更改

是的,除了我唯一一个21级航海勋章正常(1980/2000)以外其他都是远超正常数值的,都是***901的格式.
我不太懂代码方面,有什么我能提供的信息吗?

**Comment by indefined** [comment]
如果你不介意的话可以提供一下一下两个网址的内容输出
https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel?page=1&page_size=2
https://api.live.bilibili.com/xlive/app-ucenter/v1/user/GetMyMedals?page=1&page_size=2
复制打开，否则可能会报错

**Comment by URGERKING** [comment]
<details>
<summary>第一个链接</summary>
<pre>
<code>
{
  "code": 0,
  "message": "0",
  "ttl": 1,
  "data": {
    "list": [
      {
        "medal": {
          "uid": 38775300,
          "target_id": 477631979,
          "target_name": "",
          "medal_id": 227550,
          "level": 21,
          "medal_name": "粉丝团",
          "medal_color": 1725515,
          "intimacy": 1980,
          "next_intimacy": 2000,
          "day_limit": 250000,
          "today_feed": 0,
          "medal_color_start": 1725515,
          "medal_color_end": 5414290,
          "medal_color_border": 1725515,
          "is_lighted": 1,
          "guard_level": 0,
          "wearing_status": 0,
          "medal_icon_id": 0,
          "medal_icon_url": "",
          "guard_icon": "",
          "honor_icon": "",
          "can_delete": true
        },
        "anchor_info": {
          "nick_name": "vansamaofficial",
          "avatar": "http://i2.hdslb.com/bfs/face/78ce170986aa6a8536a74f20d512efb1ba01abc7.jpg",
          "verify": 0
        },
        "superscript": null,
        "room_info": {
          "room_id": 22479365,
          "living_status": 0,
          "url": "https://live.bilibili.com/22479365?accept_quality=%5B10000%5D&broadcast_type=0&current_qn=10000&current_quality=10000&is_room_feed=1&live_from=28008&live_play_network=other&p2p_type=0&playurl_h264=https%3A%2F%2Fcn-gddg-ct-01-14.bilivideo.com%2Flive-bvc%2F109187%2Flive_477631979_59058184.flv%3Fexpires%3D1655692770%26len%3D0%26oi%3D1700216862%26pt%3D%26qn%3D0%26trid%3D100025b9c135d63347bc9c25446ab0ad9745%26sigparams%3Dcdn%2Cexpires%2Clen%2Coi%2Cpt%2Cqn%2Ctrid%26cdn%3Dcn-gotcha01%26sign%3Df51dfce02304b3ea6116e2ae3eaae526%26sk%3D2935686d6cb9146c7a6a6a0b4e120e2594e074fa0760377f1a7a2b2fa0ee6443%26p2p_type%3D0%26src%3D57345%26sl%3D1%26flowtype%3D0%26source%3Dbatch%26order%3D1%26machinezone%3Dylf%26sid%3Dcn-gddg-ct-01-14%26chash%3D1%26sche%3Dban%26site%3D84e39ff54ebc2442e18834f96c0043b4&playurl_h265=&quality_description=%5B%7B%22qn%22%3A10000%2C%22desc%22%3A%22%E5%8E%9F%E7%94%BB%22%7D%5D"
        }
      }
    ],
    "special_list": [
      {
        "medal": {
          "uid": 38775300,
          "target_id": 290515513,
          "target_name": "",
          "medal_id": 119556,
          "level": 15,
          "medal_name": "旅行",
          "medal_color": 12478086,
          "intimacy": 14502,
          "next_intimacy": 40000,
          "day_limit": 1500,
          "today_feed": 1200,
          "medal_color_start": 12478086,
          "medal_color_end": 12478086,
          "medal_color_border": 12478086,
          "is_lighted": 1,
          "guard_level": 0,
          "wearing_status": 1,
          "medal_icon_id": 0,
          "medal_icon_url": "",
          "guard_icon": "",
          "honor_icon": "",
          "can_delete": true
        },
        "anchor_info": {
          "nick_name": "地球频道",
          "avatar": "http://i1.hdslb.com/bfs/face/b73ff4cb30851e970d9c5413b94b73b1df3c09b3.jpg",
          "verify": 0
        },
        "superscript": null,
        "room_info": {
          "room_id": 9196015,
          "living_status": 1,
          "url": "https://live.bilibili.com/9196015?accept_quality=%5B10000%2C150%5D&broadcast_type=0&current_qn=150&current_quality=150&is_room_feed=1&live_from=28008&live_play_network=other&p2p_type=0&playurl_h264=https%3A%2F%2Fcn-gddg-ct-01-26.bilivideo.com%2Flive-bvc%2F109187%2Flive_290515513_3522421_1500.flv%3Fexpires%3D1655692770%26len%3D0%26oi%3D1700216862%26pt%3D%26qn%3D0%26trid%3D100025b9c135d63347bc9c25446ab0ad9745%26sigparams%3Dcdn%2Cexpires%2Clen%2Coi%2Cpt%2Cqn%2Ctrid%26cdn%3Dcn-gotcha01%26sign%3D4daeb78ba403228fbd43505542ccf689%26sk%3D2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44%26p2p_type%3D0%26src%3D256%26sl%3D1%26flowtype%3D1%26source%3Dbatch%26order%3D1%26machinezone%3Dylf%26pp%3Drtmp%26sid%3Dcn-gddg-ct-01-26%26chash%3D1%26sche%3Dban%26site%3D84e39ff54ebc2442e18834f96c0043b4&playurl_h265=&quality_description=%5B%7B%22qn%22%3A10000%2C%22desc%22%3A%22%E5%8E%9F%E7%94%BB%22%7D%2C%7B%22qn%22%3A150%2C%22desc%22%3A%22%E9%AB%98%E6%B8%85%22%7D%5D"
        }
      }
    ],
    "bottom_bar": null,
    "page_info": {
      "number": 1,
      "current_page": 1,
      "has_more": true,
      "next_page": 2,
      "next_light_status": 0,
      "total_page": 23
    },
    "total_number": 45,
    "has_medal": 0
  }
}
</code>
</pre>
</details>
<details>
<summary>第二个链接</summary>
<pre>
<code>
{
  "code": 0,
  "message": "0",
  "ttl": 1,
  "data": {
    "items": [
      {
        "can_deleted": true,
        "day_limit": 1500,
        "guard_level": 0,
        "guard_medal_title": "未开启加成",
        "intimacy": 600,
        "is_lighted": 1,
        "level": 12,
        "medal_name": "蕾丝",
        "medal_color_border": 9272486,
        "medal_color_end": 9272486,
        "medal_color_start": 9272486,
        "medal_id": 53,
        "next_intimacy": 34901,
        "today_feed": 1100,
        "roomid": 11365,
        "status": 0,
        "target_id": 777536,
        "target_name": "LexBurner",
        "uname": "LexBurner"
      },
      {
        "can_deleted": true,
        "day_limit": 1500,
        "guard_level": 0,
        "guard_medal_title": "未开启加成",
        "intimacy": 2500,
        "is_lighted": 1,
        "level": 13,
        "medal_name": "电音",
        "medal_color_border": 12478086,
        "medal_color_end": 12478086,
        "medal_color_start": 12478086,
        "medal_id": 123,
        "next_intimacy": 44901,
        "today_feed": 1200,
        "roomid": 3,
        "status": 0,
        "target_id": 11153765,
        "target_name": "3号直播间",
        "uname": "3号直播间"
      }
    ],
    "page_info": {
      "cur_page": 1,
      "total_page": 23
    },
    "count": 45
  }
}
</code>
</pre>
</details>

另外我以为是B站又改玩法了结果发现了这个数值是升级历史总和,比如图示的17就是从一级到18级所需的亲密度总和(201+300+500+700+1000+1500+1600+1700+1900+5500+10000+10000+10000+15000+40000+50000+100000=249901)这个应该不是巧合吧,不知道能不能帮上忙

**Comment by indefined** [comment]
大概是B站自己脑抽了，可能确实是被用作总和了。第一个接口数据正常，等会我换成那个接口吧。这楼数据你可以删了
