### ISSUE TITLE
[Bilibili CC字幕工具] 下载番剧第二话字幕 下载下来的是第一话的

### ISSUE THREAD

**Issue by 3ak1** [indefined/UserScripts#106]
[Bilibili CC字幕工具] 下载番剧第二话字幕 下载下来的是第一话的

**Comment by indefined** [comment]
哪个番剧，能给个网址吗

**Comment by 3ak1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 3ak1** [comment]
> 

感谢大佬 可以下载了 感谢

**Comment by 3ak1** [comment]
> 哪个番剧，给一个地址吗

感谢大佬，现在可以了，谢谢！

**Comment by 3ak1** [comment]
你好 是东南亚的番剧 点下载只能下载第一话的字幕

https://www.bilibili.com/bangumi/play/ss1061066





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "indefined/UserScripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [indefined/UserScripts] [Bilibili CC字幕工具] 下载番剧第二话字幕 下载下来的是第一话的 (Issue #106)





 
哪个番剧，能给个网址吗

**Comment by indefined** [comment]
是换集判断错误，先点第一集在换到下一集会这样，现在应该修好了试试怎么样。记得换到别集点下载看看字幕是不是一样的，如果从第二集直接进去的话是不会触发错误的

**Comment by 3ak1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 3ak1** [comment]
谢谢 实测可以


Hkari
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "indefined/UserScripts"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月11日(星期二) 下午3:56
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [indefined/UserScripts] [Bilibili CC字幕工具] 下载番剧第二话字幕 下载下来的是第一话的 (Issue #106)





 
是换集判断错误，先点第一集在换到下一集会这样，现在应该修好了试试怎么样。记得换到别集点下载看看字幕是不是一样的，如果从第二集直接进去的话是不会触发错误的

**Comment by 3ak1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
