### ISSUE TITLE
[HTML5 视频截图器 0.4.18] 大几率无法截取任何YouTube视频图片

### ISSUE THREAD

**Issue by sojey** [indefined/UserScripts#107]
1. 脚本名称：HTML5 视频截图器 0.4.18

2. 脚本使用环境： Win10 21H2 内部版本19044.1826   浏览器版本 EDGE 104.0.1293.35 (正式版本) beta (64 位) 2560*1440 125%缩放

3. 问题详细描述：
大几率无法截取任何YouTube视频图片，一般截取并下载后是一个视频大小的纯黑图片。而不是视频暂停时的图像。这个问题202207月之后才发生，之前有1个月左右基本没使用过截图功能。所有不能确定到底是YouTube更新导致还是浏览器导致。

且截取其它网站，如 https://www.agemys.cc/update   https://www.dmdm2020.com/ 也有一定几率出现视频大小的黑色图片。而不是视频暂停时的图像。

**Comment by indefined** [comment]
试了一下没有复现问题，如果有具体可以触发的复现细节（视频页面链接、是通过快捷键还是工具面板）可以补充说明。
截取到黑色的图片是有可能出现的，一种情况是网站里面有多个播放器但是一些是隐藏的空内容，而脚本捕捉到了那个空的，这种情况下你可以在工具面板的那个数字下拉框里面找到多个选项，自己换一个选试试。这种情况一般发生在微博或者是套壳的外链播放器，比如你给的那两个动漫网站，但你给的网站我随便点了几个视频也没有触发问题。另一种情况是你打开了脚本工具栏捕捉了一个正常的视频，视频播放完了换了新的视频，但脚本依然捕捉了旧的那个播放完的空视频，这种情况你可以手动点一下工具面板上的刷新，脚本工具栏并不会自动刷新页面里后面加载的新视频，因为这样需要对所有网页全局监听而绝大多数情况下这种监听没有意义。
如果是用快捷键截图的那我就猜不到什么具体原因了，因为快捷键只在活动的没有遮挡的视频上方才会触发。我能猜到的唯一可能是某些奇葩的视频网站使用了画布代替视频播放器或者开发者刻意阻拦调取视频内容，不过这只是个没有证据的猜测罢了

**Comment by sojey** [comment]
真是妖怪怕师傅。我刚才用录像工具准备复现一下，居然好了！
这个问题，也伴随着其它 chrome商店里下载的视频截图类插件一同出现。我实验过几次，凡事出现黑屏的情况，无论是脚本，还是chrome插件，全部会失效。但偶尔又完全正常，我实在不清楚到底是什么触发了 在我标注的EDGE版本号中，视频截取会产生一个视频大小的黑色图片。

我谷歌了一下，有些网站说爱奇艺部分视频因为版权限制，调用一个函数导致所有浏览器内的截图功能全部失效。只能采用外部截图工具。https://developer.mozilla.org/en-US/docs/Web/API/Encrypted_Media_Extensions_API

但如果是这样，刚才实验的同一个视频，我只是把win10更新的 print screen 绑定 截图与草稿 的热键选项关闭了。

但之前没关闭的时候，也偶尔会出现，同一视频，无论是否刷新，无论怎么设置，结果就是黑图。但不知道做了什么操作，又正常工作的情况。

等我再分析下找找原因。我猜测，可能是EDGE beta的问题，微软EDGE团队非常擅长于做各类负优化，对于改进易用性方面完全不关心。

谢谢了！

**Comment by sojey** [comment]
我好像发现问题的所在了，在上述系统和EDGE浏览器版本下，硬件加速貌似就是截图黑屏的元凶。猜测版本较低的正式版则无此问题。

今天也是偶然用PotPlayer播放部分mkv或mp4视频，默认采用硬解的方式就根本无法播放或者黑屏有声音。

我的显卡是 技嘉GeForce® GTX 1070 G1 Gaming 8G。
