### ISSUE TITLE
[BiliBili CC字幕工具] 视频字幕都只能下载5分钟

### ISSUE THREAD

**Issue by CheshireCC** [indefined/UserScripts#108]
1. 脚本名称：BiliBili CC字幕工具

2. 脚本使用环境：Win11 Edge Tampermonkey 

3. 问题详细描述：下载字幕不论任何格式都只有前五分钟

![image](https://user-images.githubusercontent.com/36411617/185082191-03867c52-f730-401a-a837-1a798a8b230d.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
哪个视频能给个链接吗？我找了几个视频看都没这个问题

**Comment by GJTY** [comment]
https://www.bilibili.com/video/BV1fh411e7fA?p=7&spm_id_from=333.1007.top_right_bar_window_history.content.click&vd_source=19e9df778571f98782b33f33364dd618

**Comment by GJTY** [comment]
难道我没用会？

**Comment by indefined** [comment]
看了一眼这个视频确实有这个问题，大概是B站用了新的API，我晚些查一下看看怎么修吧

**Comment by GJTY** [comment]
好的，大佬有时间搞一下，我觉得会不会是双语字幕的原因呢？？

**Comment by indefined** [comment]
是新版播放器的分P问题，不知道怎么搞的总之现在播放器给的信息总是指向第一个分P，虽然找到了处理方法但是挺脱裤子放屁的。已更新可以检查一下是不是能用了

**Comment by GJTY** [comment]
好的，感谢
