### ISSUE TITLE
[BiliBili CC字幕工具] 没有本地字幕选项

### ISSUE THREAD

**Issue by cklemodren** [indefined/UserScripts#109]
脚本名称：BiliBili CC字幕工具 

    脚本使用环境：Win10 1079 Firefox 104.0.2 Tampermonkey

    问题详细描述：没有本地字幕选项
![bandicam 2022-09-17 21-47-34-841](https://user-images.githubusercontent.com/103050749/190860491-6677fa17-e14d-48e3-9992-b830dc2eff83.jpg)

**Comment by indefined** [comment]
B站更新了播放器，新版播放器已经没有办法使用本地字幕了

**Comment by jp5865** [comment]
好吧
