### ISSUE TITLE
HTML5视频截图器快捷键支持

### ISSUE THREAD

**Issue by amagaa** [indefined/UserScripts#11]

**Comment by indefined** [comment]
是指截图工具还是哪个脚本？截图工具有计划做快捷键，但是太懒所以一直没动手，设置默认基本是不可能的，因为是通用脚本无法确定网页情况如果默认启用很容易出现冲突

**Comment by amagaa** [comment]
就是bilibili截图的那个脚本。每次打开视频都要按几按好麻烦啊。动动啦亲~造福大众啦亲~~大家会很感谢你的~~

**Comment by amagaa** [comment]
大家会很感谢你的~~不知为何上面的好像有条横线，再发多次。造福大众啦亲~~冥冥之中自会有回报的！

**Comment by amagaa** [comment]
就是bilibili截图的那个脚本。每次打开视频都要按几按好麻烦啊。动动啦亲~造福大众啦亲大家会很感谢你的~~

**Comment by indefined** [comment]
已更新，这脚本似乎朝着没预料的播放器外壳方向发展了……变化较大可能存在比较严重的BUG和冲突隐患，如果有问题发生请继续反馈

**Comment by amagaa** [comment]
谢谢大佬！！

发送自 Windows 10 版邮件应用

发件人: indefined
发送时间: 2019年9月18日 20:41
收件人: indefined/UserScripts
抄送: amagaa; Author
主题: Re: [indefined/UserScripts] HTML5视频截图器快捷键支持 (#11)

已更新，这脚本似乎朝着没预料的播放器外壳方向发展了……变化较大可能存在比较严重的BUG和冲突隐患，如果有问题发生请继续反馈

**Comment by amagaa** [comment]
如果能让“截图”和“↓”也有快捷键，就更好了……

**Comment by indefined** [comment]
> 如果能让“↓”也有快捷键，就更好了……因为我通常是用“↓”……

按住shift同时按下截图快捷键会尝试直接下载，设置窗口悬停有提示，个人觉得弄太多快捷键容易冲突所以能合并就合并了

**Comment by amagaa** [comment]
但是这个脚本的主要功能是截图吧，其他功能“HTML5播放器增强插件”也有……
可以设置成全屏也能用吗？

现在除了“开启/关闭工具栏”，其他快捷键好像都失效了 ……

**Comment by indefined** [comment]
所以我才说这个脚本加了快捷键好像朝着播放器外壳发展了，一开始并没有打算弄这么复杂，整套快捷键判定设置和多配置逻辑几乎已经比原先整个脚本的功能还大了。
勾上播放器悬停有效保存就能不打开工具栏直接在部分视频上用了，但是很容易冲突，也不一定适用于所有视频，我并不知道有多少网站能用多少不能用，所以没有默认启用，建议只在确认没有冲突的常用网站上自己勾选并使用“保存本网站”按钮保存，设置窗口上大大部分内容悬停都有提示。
至于直接下载截图是否要需要独立快捷键，我个人觉得没什么太大必要，多按一个按键并不是很复杂

**Comment by amagaa** [comment]
直接下载比较快，一般都会选这个吧……

最新版的“截图工具栏有效”和“播放器悬停有效”，好像选择不了。

**Comment by indefined** [comment]
已增加。`工具栏有效`本来就是不可以更改的，只是放在那里提示有这个功能，`播放器悬停有效`是可以改的，不过原先那个文字标签并没有绑定在复选框上，需要直接勾复选框，现在已经绑定了。

**Comment by indefined** [comment]
顺便有个值得一提的BUG，如果没有勾选`播放器悬停有效`，开启工具栏之后如果有选中视频并用鼠标点击关闭工具栏会导致整个网页全局可以用快捷键操作被选中视频，只有鼠标不在工具栏上用快捷键关掉工具栏才不会有这个现象，姑且也算个神经病的功能所以没有修掉它
