### ISSUE TITLE
[网易CC直播净化]强制开启弹幕

### ISSUE THREAD

**Issue by What-a-mess** [indefined/UserScripts#110]
目前CC会在特殊时期关闭播放器的弹幕功能，有点影响使用体验
解决方案是可以执行
`window.ccplayer.player.comment.commentSwitch=true;`
来手动开启弹幕
本想将这个功能加入CC直播净化的脚本，但是发现这个脚本更多关注于改变渲染样式来净化页面，而不是执行代码来操作页面，不知道加入这个功能是否有违该脚本的初衷

**Comment by indefined** [comment]
没有加入的计划。本质是个挺独立的功能而且你已经实现了自己新建一个脚本应该更合适，如果有需要的话你自己独立发布出去用的人也会更方便找到
