### ISSUE TITLE
[bilibili网页端添加APP首页推荐] 提示“请求app首页失败 code -663</br>msg 鉴权失败，请联系账号组”

### ISSUE THREAD

**Issue by yinzhefuyun** [indefined/UserScripts#114]
1. 脚本名称：bilibili网页端添加APP首页推荐-0.6.22

</body>
</html>

2. 脚本使用环境：win11 chrome 107

3. 问题详细描述：
提示“请求app首页失败 code -663</br>msg 鉴权失败，请联系账号组”

<details>
<summary>错误报告</summary>
<pre>
<code>

请求app首页失败 {code: -663, message: '鉴权失败，请联系账号组', ttl: 1}
</code>
</pre>
</details>

**Comment by indefined** [comment]
设置里删除鉴权然后重新获取就行了。首先说明这个提示是B站给的不是我给的，但这个提示确实挺离谱的，本来鉴权应当有一个月有效期的，而且鉴权失效之前也不是这个提示，但最近一两天很频繁失效，应该是B站内部对鉴权动了什么手脚，但不管怎么样除非B站回心转意否则我这边是没什么办法的，如果B站认真动手脚的话视情况这个脚本可能会完全失效不能用

**Comment by yinzhefuyun** [comment]
> 设置里删除鉴权然后重新获取就行了。首先说明这个提示是B站给的不是我给的，但这个提示确实挺离谱的，本来鉴权应当有一个月有效期的，而且鉴权失效之前也不是这个提示，但最近一两天很频繁失效，应该是B站内部对鉴权动了什么手脚，但不管怎么样除非B站回心转意否则我这边是没什么办法的，如果B站认真动手脚的话视情况这个脚本可能会完全失效不能用

试过了，不起作用
步骤：先退出授权，再退出b站登入，再登入b站，再授权，然后刷新还是这样的提示，第一次授权+用F5可以获取一次，然后无论是点击“加载更多”还是F5都是一样的报错，但愿过几天b站自己会好

**Comment by indefined** [comment]
不是很理解，我这边重新获取之后至少是能用一段时间的，虽然比以前短很多。退出帐号没什么必要，F5和电机加载更多的结果也是一样的。如果说获取之后加载一次就会报错那大概率是这个脚本的请求操作触发了B站的什么机制导致他拉黑了鉴权，也就是可能B站盯上电脑端的脚本了。你可以试一下再删除获取一次看看还是不是一次就报错，还是这样的话你只能等几天看看了。我这边也观察一下表现，如果出现的话我多尝试几个伪装APP的操作看看有没有效果，但是没法保证能解决

**Comment by deYangar** [comment]
![image](https://user-images.githubusercontent.com/70438628/206352857-28be901a-71da-4b3b-a881-db8dffa8b2a2.png)
今天好像完全不太行了，这是删除授权，重新获取后的情况

**Comment by indefined** [comment]
现在看这个鉴权失败似乎和授权被拉黑没有关系，完全是行为判断，所以报错也没有必要删除重新获取授权，没有用处。刚开始的时候我第一次打开会报错点刷新就没问题，这几天我这边没见到报错了也不知道是伪装有效还是这个鉴权是对每个人不同的。
总之我推个伪装更新吧但没法保证有用

**Comment by deYangar** [comment]
好的好的，我这边的情况是第一次出现这种情况，也就是issues里看的19天前，之后的一周就没问题了，能正常获取，然后从昨晚还是今早开始就这样了，今早第一次刷新没问题，之后的就全部不能获取

**Comment by yinzhefuyun** [comment]
> 好的好的，我这边的情况是第一次出现这种情况，也就是issues里看的19天前，之后的一周就没问题了，能正常获取，然后从昨晚还是今早开始就这样了，今早第一次刷新没问题，之后的就全部不能获取

我昨晚又出现了，没办法，有时候过一天又好了

**Comment by indefined** [comment]
报错就多点几次加载更多吧，目前情况看这个风控系统完全就是瞎抽风完全找不到它的规律

**Comment by hukewei2001** [comment]
> 没有头绪，可能这个接口已经废了。旧版APP大概已经不能登录了所以也没法测，我试了全签名参数结果是一样的。等几天看有没有变化吧，真废了只能换接口了，首页倒是已经有一个了，问题是不喜欢的接口也一起废了，真换接口还要找个旧手机抓包挺蛋疼的

大佬辛苦了

**Comment by YJL12345** [comment]
等作者更新

**Comment by indefined** [comment]
没有解决问题有用的信息就不要回复无关内容了，这里不是贴吧微博，议题是追踪问题用的，参与的人都会收到通知，回复无关内容等于整天往别人邮箱里塞垃圾。收到这条回复知道就好，也别给我回复知道了，知道了也是无关内容

**Comment by MotooriKashin** [comment]
> 真换接口还要找个旧手机抓包挺蛋疼的

最近在app端抓了很多数据，正好可能有能提供帮助的。系统meizu 16，Android 10，app我一直使用的安卓国内版6.40.0，应该不会有失效的问题。
```
GET /x/intl/feed/index?appkey=1d8b6e7d45233436&build=6400400&c_locale=zh_CN&channel=master&from=1&login_event=0&mobi_app=android&platform=android&s_locale=zh_CN&statistics=%7B%22appId%22%3A1%2C%22platform%22%3A3%2C%22version%22%3A%226.40.0%22%2C%22abtest%22%3A%22%22%7D&ts=1671071142 h2
Host: app.bilibili.com
buvid: XYF136DF29B8802DA10CC2C8B6D3804F828DA
device-id: NgZgUGVXYQQyUDIDfwN_
fp_local: 857d4c6fcdec82bbe9ef48f64fc60d7f2022083120151996008c9cc8d2f531b1
fp_remote: 857d4c6fcdec82bbe9ef48f64fc60d7f2022083120151996008c9cc8d2f531b1
session_id: bdfcc00b
env: prod
app-key: android64
user-agent: Mozilla/5.0 BiliDroid/6.40.0 (bbcallen@gmail.com) os/android model/16th mobi_app/android build/1 channel/master innerVer/6400410 osVer/10 network/2
accept-encoding: gzip
```

`access_key`因为隐私原因我去掉了，并且sign一并去掉了，重新签名一下应该可以直接获取返回值。  
不喜欢那个我没抓，因为对某个视频点不喜欢总感觉有种罪恶感，不过对比这个api，应该只是在url路径上多了个`intl/`？

ps: 话说`intl/`应该是play版app的api特征，为何国内版也有这个？
ps2: 这个app是我基于原版进行了修改的，去掉了抓包限制，就算在高版本Android上也一样能使用中间人抓包（限Android端的Packet Capture和HttpCanary，PC端的没试过），如有需要我可以分享出来。

**Comment by indefined** [comment]
感谢，能否分享一下app，我抓一下不喜欢的接口

**Comment by yinzhefuyun** [comment]
> 感谢，能否分享一下app，我抓一下不喜欢的接口

我找了一下b站6.40.0不知道你需要的是那一个版本，32位的64位的我都列出来了
原版64位   #android64   -这个版本我们对使用体验进行了一轮优化并解决了一些bug~~   https://dl.hdslb.com/mobile/pack/android64/6275725/iBiliPlayer-apinkRelease-6.40.0-b6275725.apk
原版32位   #android   -这个版本我们对使用体验进行了一轮优化并解决了一些bug~~   https://dl.hdslb.com/mobile/pack/android/6275736/iBiliPlayer-apinkRelease-6.40.0-b6275736.apk
原版64位   #android64   -这个版本我们对使用体验进行了一轮优化并解决了一些bug~~   https://dl.hdslb.com/mobile/pack/android64/6287414/iBiliPlayer-apinkRelease-6.40.0-b6287414.apk
原版32位   #android   -这个版本我们对使用体验进行了一轮优化并解决了一些bug~~   https://dl.hdslb.com/mobile/pack/android/6287420/iBiliPlayer-apinkRelease-6.40.0-b6287420.apk

**Comment by MotooriKashin** [comment]
> 感谢，能否分享一下app，我抓一下不喜欢的接口

`https://www.123pan.com/s/D8tUVv-ZZEg3提取码:1T7I`

作为日常使用，打包了漫游，所以启动有点慢，不要介意。

**Comment by indefined** [comment]
日了狗，抓了一下发现不喜欢的接口没变，但是我之前用全部的参数签名放网页端却用不了。逐个参数对比，发现B站是校验了appkey和access_key的对应关系，因为我用来获取access_key的appkey和APP用的不一样……等会更新上去吧
