### ISSUE TITLE
[微博自动展开评论脚本]大佬,新版微博还能写个自动展开评论吗?谢谢

### ISSUE THREAD

**Issue by gghrgr** [indefined/UserScripts#115]

**Comment by indefined** [comment]
> > 大佬,新版微博还能写个自动展开评论吗?谢谢
> 
> 新版微博自动会展开评论，但是评论的楼中楼是弹窗的不可能自动展开，技术问题不说真展开了不是一堆窗了。微博展开这个脚本已经过期不再继续维护

**Comment by gghrgr** [comment]
了解了,谢谢
