### ISSUE TITLE
[Bilibili CC字幕工具] 沒有出現下載按鈕

### ISSUE THREAD

**Issue by Tai-Wu-Qing-La-Rong-Rong-Shu** [indefined/UserScripts#116]
<html>
<body>

如題  沒有出現下載按鈕
麻煩你測試一下 謝謝

浏览器 : Vivaldi 5.7.2921.53 (Stable channel) (64 位元)
脚本管理器 : Tampermonkey® 
脚本的版本 : 0.5.33
動畫網址 : https://www.bilibili.com/bangumi/play/ep731723

<img width="314" alt="cantdl" src="https://user-images.githubusercontent.com/93402763/220793583-3db0df5d-30d2-4227-b751-6280415df7bd.png">

-- | --

</body>
</html>

**Comment by indefined** [comment]
播放器内右键更新历史的版本号是多少？这个动画页面你是使用那个脚本解除限制的还是港澳台那边直连可以直接观看的？

**Comment by akkii7788** [comment]
有出现同样的情况，应该也是这周才失效的，历史版本3.27.1-e85c9522，本人是挂代理开港澳台页面，不知道原题主了

**Comment by indefined** [comment]
试了一下在代理或者本地直连情况下新版的播放器在非chrome浏览器网页上获取不到视频信息，所以脚本无法运行，应该是B站自己对不同浏览器的兼容搞出了问题，目前在没有折腾出直接解决方案，替代方案要么使用chrome（EDGE）要么使用脚本绕过限制（解除B站区域限制的脚本会降级播放器的版本所以可以正常运行

**Comment by akkii7788** [comment]
我现在就在用chrome，版本旧了点（96），也是没法运行，我尝试一下解除限制脚本的方法

**Comment by indefined** [comment]
不清楚和浏览器有什么关系，我又试了一下在Vivaldi里是正常的（UA是Chrome108）但是火狐里无法运行，更改UA并没有区别，而且和你们的报告都不一致，播放器版本号都一样，想不出具体哪里的问题

**Comment by Tai-Wu-Qing-La-Rong-Rong-Shu** [comment]
<html>
<body>

抱歉  拖這麼久才回復

Vivaldi | 5.7.2921.60 (Stable channel) (64 位元)
修訂版本 | b442729c9d1d213fb300493d3f89eba4987bd132
作業系統 | Windows 10 Version 22H2 (Build 19045.2364)
JavaScript | V8 11.0.226.16
使用者代理(vivaldi預設) | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

播放器历史版本 3.27.1-e85c9522

我是直連台港澳，沒有掛代理，也沒有使用脚本解除限制


</body>
</html>

**Comment by indefined** [comment]
想起一个不知道有没有关系的点：播放器的设置按钮上——更多设置——播放策略 选择AVC， 然后刷新页面试试能不能用？之前有过B站的HEVC播放器策略会导致脚本无法使用，但不知道现在怎么样。已经确定了至少在我的电脑上B站的同一个播放器版本有不同的实现，但我没有找到导致的原因，如果更改设置不能用目前也想不出什么解决方法了

**Comment by akkii7788** [comment]
我这默认是AVC，也不行。目前暂时用解除地域限制脚本后可以继续用。

**Comment by indefined** [comment]
推送了一个新版本，不确定是否解决新番剧问题

**Comment by akkii7788** [comment]
谢后续更新，更新后使不使用限制解除脚本也能看到字幕下载按钮了
![1](https://user-images.githubusercontent.com/126534691/231036186-1e83e17d-8d0a-4335-b878-81046873afe0.png)

**Comment by Tai-Wu-Qing-La-Rong-Rong-Shu** [comment]
> 推送了一个新版本，不确定是否解决新番剧问题

試了一部新番能正常下載
辛苦你了  謝謝

<img width="698" alt="OKOK" src="https://user-images.githubusercontent.com/93402763/235328684-9f3ead8c-315f-4192-9d17-076d45563d39.png">
