### ISSUE TITLE
[Bilibili直播间工具] 全屏礼物栏隐藏BUG（B站新版样式）

### ISSUE THREAD

**Issue by Mishasama** [indefined/UserScripts#118]
1. 脚本名称：Bilibili直播间工具

2. 脚本使用环境：Win10 | Chrome 111.0.5563.65 | Tampermonkey 4.18.1

3. 问题详细描述：

取消勾选后无法正常显示礼物栏，会遮挡直播画面，应该是最近B站新增了赌博模块导致的。
![image](https://user-images.githubusercontent.com/54498172/225838864-4fa973a5-9c71-4571-a703-b606f0e5ca03.png)

![image](https://user-images.githubusercontent.com/54498172/225837706-484473f3-a1b5-4cf2-b53b-fe23b7a04c69.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
取消了应该是完全不显示才对啊，我试了几个直播间至少开关上应该是正常的。在没有那个魔法奇遇什么的直播间和以前一样，有魔法奇遇的礼物栏和底边对齐有问题，如果开启全屏弹幕发送框会发生重叠，其它的暂时没发现问题。你是在哪个直播间出的问题？我挺久没看B站直播了所以也没办法去注意脚本问题，可能以后考虑停止维护这个脚本

**Comment by indefined** [comment]
修了个礼物栏对齐，但大概率和你说的不是一回事

**Comment by indefined** [comment]
嗯……看了一下是B站自己内置了全屏时显示礼物栏功能，和脚本带的功能冲突了，我前两天看的时候还没有，应该是灰度测试刚上的。不得不说B站这玩意做得是真丑。晚些调试一下把脚本重复的功能删了

**Comment by Mishasama** [comment]
> 嗯……看了一下是B站自己内置了全屏时显示礼物栏功能，和脚本带的功能冲突了，我前两天看的时候还没有，应该是灰度测试刚上的。不得不说B站这玩意做得是真丑。晚些调试一下把脚本重复的功能删了

哈哈，照这么说我还挺“灰”的……2023年头我就开始有这玩意了，只是一直没出现遮挡问题就没说了。这次加上赌博模块给我挡上了没法看了只能求助大佬了😂

![image](https://user-images.githubusercontent.com/54498172/226525365-6668941e-ae19-4180-9add-3effebc81201.png)
但问题也来了，在打开礼物栏的时候弹幕输入没了……
呃……想修就修吧，并不是什么大问题，不修也能用就是了。

**Comment by indefined** [comment]
这个修不了，现在那个全屏弹幕发送框是原生的功能，我只是加了一条在网页全屏且隐藏侧边栏的时候显示出来的样式，但是网页全屏打开礼物栏的时候那个弹幕发送框就销毁了，我也不知道为什么它这么设计的。进入全屏再退出又恢复了，开关礼物栏它还可能会卡在半中间，应该是B站自己写的BUG吧，没有额外写一个弹幕发送框的打算

**Comment by Mishasama** [comment]
> 应该是B站自己写的BUG吧

典型的自己从来都没用过自己做出来的玩意，业界毒瘤咱就不给他擦屁股了😒
