### ISSUE TITLE
[bilibili网页端添加APP首页推荐] 现在用的app接口推荐的内容和手机客户端上推荐的有明显差异

### ISSUE THREAD

**Issue by u2shana** [indefined/UserScripts#119]
大概就这个月开始的吧，有些推荐类型手机上一刷就有，脚本推荐刷烂了一条没见到
重新授权也没太大变化

不知道是不是我个人的问题

**Comment by indefined** [comment]
没有更换API测试的打算，这个脚本从各种意义上都很落后，彻底失效只是时间问题，或许你可以尝试一下新界面和新API的https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend
