### ISSUE TITLE
[哔哩哔哩港澳台使用] 无法在僅限港澳台地區的番剧内下载字幕

### ISSUE THREAD

**Issue by myjdem** [indefined/UserScripts#120]
视频右键历史更新版本3.27.1-e85c9522
使用的是chrome 版本 112.0.5615.50（正式版本） （64 位）
使用区域限制脚本或者是clash for windows全局代理都没有下载
![image](https://user-images.githubusercontent.com/76983930/230963663-877ae5ec-6dc1-4bbf-ba73-79a0deae74bc.png)
![image](https://user-images.githubusercontent.com/76983930/230963689-63ea6bc1-0b1f-4269-96d5-4e51ff13d77c.png)
国内的视频倒是可以下载字幕
![image](https://user-images.githubusercontent.com/76983930/230963788-ae013058-cdfb-4aad-928b-a8db48bf6a7c.png)
配合哔哩哔哩旧版播放页面可以下载
![image](https://user-images.githubusercontent.com/76983930/230964082-cf7cbf3a-c049-4145-8a1c-58286c923dc8.png)
附脚本链接下载https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5
希望可以找出是什么问题并修复

**Comment by indefined** [comment]
Duplicate of #116 感觉你使用解除限制的脚本时没有关闭代理，解除限制的字幕列表和你图上不一样的。这个问题和 #116 重复所以有新问题在那边回复就行了
