### ISSUE TITLE
[获取 access_key] 没有获取匹配的密钥

### ISSUE THREAD

**Issue by xuyan-tail** [indefined/UserScripts#121]
![image](https://github.com/indefined/UserScripts/assets/25627516/fe0910fd-8588-401a-80f5-827c9a26ab83)
点击获取access_key 其实没有获得匹配的密钥  需要怎么样才可以获取 有没有教程

**Comment by indefined** [comment]
你找错地方了，新版作者的项目在这里 https://github.com/magicdawn/bilibili-app-recommend
正常来说，密钥获取失败要么是你没登录帐号，要么就是接口失效了，我最近也没测过这接口是不是失效了

**Comment by xuyan-tail** [comment]
> 你找错地方了，新版作者的项目在这里 https://github.com/magicdawn/bilibili-app-recommend 正常来说，密钥获取失败要么是你没登录帐号，要么就是接口失效了，我最近也没测过这接口是不是失效了

感谢  不过想问下   所谓的登陆账号就是pc端登陆b站账号对吧  这点我是登陆了的
