### ISSUE TITLE
[app接口获取授权，超时] 

### ISSUE THREAD

**Issue by HCYLSOOY** [indefined/UserScripts#123]
【bilibili网页端添加APP首页推荐】这个脚本，现在获取授权，一直显示超时，但通过

“https://passport.bilibili.com/login/app/third?appkey=27eb53fc9058f8c3&api=https:%2F%2Fwww.mcbbs.net%2Ftemplate%2Fmcbbs%2Fimage%2Fspecial_photo_bg.png&sign=04224646d1fea004e79606d3b038c84a" 里的confirm_uri

是可以获得access_key数据的，
是否能更新一下脚本，麻烦作者了。
或者是否可以麻烦告知一下，通过网页获取的access_key应该填在脚本的哪里，怎么填写，谢谢。

**Comment by indefined** [comment]
我以为首页已经全部强制更新为新版了 :思考:
B站现在禁止嵌入式网页跨域了好像所以获取授权失败，要更新的话只能弹出窗口获取，这样不太友好，而且这个脚本现在能用的人应该很少了。
网页获取的access_key可以填在脚本管理器里的数据存储，以篡改猴为例在脚本管理器里打开这个脚本，选择存储标签，在中间某一行填上
```
    "biliAppHomeKey": "你的access_key",
```
点击保存。
如果是暴力猴那么打开脚本之后选择数据标签，键名填biliAppHomeKey键值填你获取到的access_key

**Comment by indefined** [comment]
不需要后面的mid什么的，我推送了一个更新你试一下吧，现在点击获取会弹出要给小窗口，如果被拦截的话要同意不然还是会获取失败

**Comment by HCYLSOOY** [comment]
> 不需要后面的mid什么的，我推送了一个更新你试一下吧，现在点击获取会弹出要给小窗口，如果被拦截的话要同意不然还是会获取失败
ok，更新0.6.25后搞定了，非常感谢。
还是旧版首页好，特别是你的这个推荐脚本，主要是能保存推荐数量，特别好用。
感恩！

**Comment by HCYLSOOY** [comment]
> 不需要后面的mid什么的，我推送了一个更新你试一下吧，现在点击获取会弹出要给小窗口，如果被拦截的话要同意不然还是会获取失败

还有，b站旧版页面也是通过篡改猴里的脚本实现的
