### ISSUE TITLE
[bilibili网页推荐]是否能更换app推荐接口？

### ISSUE THREAD

**Issue by HCYLSOOY** [indefined/UserScripts#125]
首先请原谅我对您的这个脚本情有独钟，
目前我使用篡改猴里的“Bilibili回到旧版”来达到b站网页端回到旧版首页的功能，
再配合您的脚本来使用网页端推荐功能。
8月份曾经麻烦过您更新了一版，修复了获取key超时的问题。（最新的0.6.25版本）
目前0.6.25版本仍然能正常获取key，
但是推荐内容跟app端已经完全不同，（应该是从10月份开始出现的问题）

==

我尝试用新版首页和“bilibili-app-recommend”这个脚本，
“bilibili-app-recommend”能够正常显示app端推荐内容，

我看了“bilibili-app-recommend”这个脚本获取app接口的更新说明，
好像是换成了v2版本，

https://github.com/magicdawn/bilibili-app-recommend/issues/18

“可以用现在APP使用的接口 https://app.bilibili.com/x/v2/feed/index，不必换到PC首页推荐接口
仅需appkey和access_key就可以获取内容
如https://app.bilibili.com/x/v2/feed/index?appkey=27eb53fc9058f8c3&access_key=********************************
响应内容包含稍候再看/不喜欢/反馈等”

==

但由于我对旧版首页和您的脚本太过念旧，始终放不下，
所以是否能够麻烦您更新一下接口？
万分感激！

**Comment by indefined** [comment]
没有更换接口的打算，主要是这个脚本也实在过老了我都不知道还有几个人在用，个人也更喜欢旧版的推荐内容而不是新版的。有兴趣的话可以自行尝试合并这个PL，但是这个更改挺老了我也不知道合并起来顺利不顺利https://github.com/indefined/UserScripts/pull/88

**Comment by HCYLSOOY** [comment]
> 没有更换接口的打算，主要是这个脚本也实在过老了我都不知道还有几个人在用，个人也更喜欢旧版的推荐内容而不是新版的。有兴趣的话可以自行尝试合并这个PL，但是这个更改挺老了我也不知道合并起来顺利不顺利#88

我是纯外行，不会改，
添加了v2之后就是“请求app首页发生错误 TypeError: Found non-callable @@iterator”，
难道这个脚本就要这么无疾而终了吗，
但还是谢谢你这几年来开发和维护脚本的辛劳。
