### ISSUE TITLE
[bilibili CC字幕]请求将CC字幕转为VTT的功能

### ISSUE THREAD

**Issue by jhdxr** [indefined/UserScripts#128]
Firefox的画中画[只支持VTT的字幕](https://blog.mozilla.org/en/products/firefox/firefox-picture-in-picture-rolls-out-subtitles/)，gresfork上看了一圈感觉这个脚本最接近了，不知道能否增加这个功能？

p.s. 理论上来说这个功能其实可以通过 下载CC + CC转VTT + 上传VTT实现（我没有深挖背后的实现，如果现在脚本/B站是使用`<track>`的话应该能直接复用，否则这块也是需要重新实现的）。 我注意到新版的编辑器已经不支持本地上传了，能问下主要的原因是啥嘛？因为同样的原因可能阻碍这个CC转VTT的可行性

**Comment by indefined** [comment]
不支持本地的原因是B站新版的播放器已经没有暴露调用字幕的接口，B站的字幕是自行实现的，用的不是原生的h5视频字幕轨，在chrome画中画里也是不显示的。调用字幕接口虽然不知道能否注入挟持，但是按本人的能力估计够呛，而且按你的需求原生的字幕实际也不能用。直接自行实现一个H5视频字幕轨并不难，麻烦的是界面和设置选项，下载CC + CC转VTT 都是可行的，但增加一个上传VTT的功能目前没什么动力实现，因为新增的字幕轨会和B站播放器自己的字幕同时存在，而且样式大小颜色这些可能看着会很奇怪，我又懒得去做一个界面来调整它们

**Comment by indefined** [comment]
f4a7fc9 VTT格式下载已支持，不过应该不是你想要的东西。
上传本地字幕你可以随便找类似+sub这样的扩展，这类扩展基本都是使用H5视频原生字幕轨来实现的，可以支持任意网站的H5视频，可以在画中画里显示，而且也不局限于上传VTT格式所以你不用更新直接下载SRT也可以用（实际上是这种扩展会读取ASS/SRT等常用字幕格式并且自己把它们转成VTT），你可以自己找个顺眼的安装。
https://addons.mozilla.org/zh-CN/firefox/addon/plussub/
说实话如果不管显示效果的话实现一个这种字幕轨非常简单，但是嗯……你自己装一个折腾折腾也会知道如果不调整的话这种字幕轨显示效果会非常奇怪，所以完全没有重复造轮子的冲动
