### ISSUE TITLE
[Bilibili CC字幕工具]请求在港澳台新版播放页面下载字幕

### ISSUE THREAD

**Issue by FLASHRUNFAST** [indefined/UserScripts#129]
现在港澳台番剧的播放页面好像换了一个新版的，字幕旁边没有下载的选项了
![{46F94EB8-D8A5-4da7-A289-BC2019230114}](https://github.com/indefined/UserScripts/assets/48755277/cbccd300-6102-4790-9bc4-3102de14a7cd)

**Comment by indefined** [comment]
麻烦给个番剧地址，以及你是通过什么方式看的，代理，本地直连，还是脚本？

**Comment by indefined** [comment]
![QQ截图20240112214904](https://github.com/indefined/UserScripts/assets/37869994/611036bb-54ec-4a14-8979-6559467141aa)
以及在播放器里右键查看一下播放器版本号

**Comment by indefined** [comment]
已推送更新，可以试一下

**Comment by FLASHRUNFAST** [comment]
谢谢，更新以后可以了
观看方式：代理
番剧地址：https://www.bilibili.com/bangumi/play/ep809811?spm_id_from=333.999.0.0
播放器版本：
![QQ截图20240113182413](https://github.com/indefined/UserScripts/assets/48755277/90c62b7b-eb13-42c3-b0a4-6383b0ac3d19)
