### ISSUE TITLE
直播间内20硬币购买勋章，切换勋章，切换头衔失效

### ISSUE THREAD

**Issue by wanzuiqingfeng** [indefined/UserScripts#13]
![image](https://user-images.githubusercontent.com/55115829/66009377-caf55000-e4ec-11e9-9205-2374835ae05b.png)
![image](https://user-images.githubusercontent.com/55115829/66009396-d6487b80-e4ec-11e9-8abd-1d737f45f551.png)

**Comment by indefined** [comment]
暂时已修复，看上去是特殊时期的弹幕发送框调整，不知道后续还会不会变回来，有问题继续反馈
