### ISSUE TITLE
[Bilibili CC字幕工具] 错误的显示了上一个视频的字幕

### ISSUE THREAD

**Issue by akira0245** [indefined/UserScripts#130]
1. 脚本名称：
Bilibili CC字幕工具 0.5.39

2. 脚本使用环境：
Win11 篡改猴版本5.1.0 Chrome版本 123.0.6312.106（正式版本） （64 位）

3. 问题详细描述：
在视频播放页点击其他视频进入新视频后，在新视频中里打开字幕工具，其中显示的字幕仍是上一个视频的字幕内容。
（似乎只有在前一个视频里没有打开过字幕工具，到第二个视频才打开时候才会发生）

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
0.5.40已更新，可以试一下

**Comment by xuexigithub** [comment]
创作者没有打开cc字幕情况怎么下载字幕啊

**Comment by indefined** [comment]
没有字幕按钮的情况下就是没办法下载字幕的，只有软外挂字幕可以下载，内嵌字幕是没办法下载的。
