### ISSUE TITLE
userScirpt 无效

### ISSUE THREAD

**Issue by kshq1996** [indefined/UserScripts#135]
在 userScirpt 中无效

<img width="1599" alt="image" src="https://github.com/user-attachments/assets/dcb68696-7285-40c1-a640-03e895ab5854">

**Comment by indefined** [comment]
新版本到这边反馈 https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend
个人认为应该是userscript脚本管理器缺少对GM函数的完整支持导致的
