### ISSUE TITLE
希望能添加一个能在主页查看历史记录的功能

### ISSUE THREAD

**Issue by Laughter0934** [indefined/UserScripts#136]
bilibili app recommend

目前网页版b站查看历史记录有些麻烦,而且只能显示一部分最新的历史记录,希望能添加一个能在主页查看历史记录的功能

**Comment by indefined** [comment]
旧版脚本现在没有加入任何新功能的打算。我猜你期望的是新版本的脚本上的功能需求，可以到这里反馈https://github.com/magicdawn/bilibili-app-recommend/issues
