### ISSUE TITLE
bilibili网页端添加APP首页 新版适配问题

### ISSUE THREAD

**Issue by indefined** [indefined/UserScripts#15]
已适配更新。目前新旧版共用主框架代码共存，所以如有新版修改了样式导致的旧版页面问题也在此话题反馈。

已知问题：

1. 0.6.0重构之后至少已经不再兼容Chrome49了，大概Chrome55以下都无法运行，后续版本大概也不会再有向下兼容。如果仍然有使用旧版浏览器的用户，目前0.5.8版本在旧版网页仍旧可以运行，但无法保证后续可用
2. 如果推荐框宽度和推荐内容数量不成整倍数，（比如低分辨率时一行4个推荐，一次加载10个推荐会有2行余两个）最后不足一行的内容将会左右对齐中间留下很大空白，这是新版页面的弹性布局方式造成的，目前不打算进行修正

如有已知问题以外的其它BUG或者没有生效请说明使用的浏览器、脚本管理器版本，Chrome按Ctrl+Shift+J键，Firefox按Ctrl+Shift+K键查看控制台是否有红色错误报告

此外新版的页面针对不同屏幕分辨率有自适应样式，由于本人没有那么多实机分辨率的显示器测试所以如有显示异常请反馈错位的截图及所使用的浏览器、分辨率

>已收到新版cookie反馈，有效识别字段为INTVER=1，目前需要一点时间进行适配
>
>>我遇到了新版适配问题，首页确实能看到动画模块，console红色错误提示如下
>>...
>>_Originally posted by @aoxu in https://github.com/indefined/UserScripts/issues/10#issuecomment-546558005_
>

**Comment by aoxu** [comment]
辛苦了，期待更新~

**Comment by indefined** [comment]
已更新，如有BUG请反馈所使用的浏览器、屏幕分辨率

**Comment by aoxu** [comment]
更新后实测已经完全正常，包括“不感兴趣”功能，目前没有发现bug~
