### ISSUE TITLE
哔哩哔哩网页版界面更新 首页推荐失效了

### ISSUE THREAD

**Issue by liuyandashen** [indefined/UserScripts#17]
哔哩哔哩网页版界面更新 首页推荐失效了

**Comment by indefined** [comment]
应该已经在0.6.0中适配，如果你确定已经更新到最新版没有生效请说明使用的浏览器、脚本管理器版本，按F12查看控制台是否有错误报告。已有关于本问题的话题#15 相关问题请在到该话题中集中反馈，本反馈关闭
