### ISSUE TITLE
脚本乱码

### ISSUE THREAD

**Issue by Evansmay** [indefined/UserScripts#18]
使用chrome78，屏幕分辨率为1980*1080
![1](https://user-images.githubusercontent.com/58456141/70020598-3bd9e680-15c8-11ea-8912-55a37fdc0ce8.jpg)

**Comment by indefined** [comment]
使用什么方法安装的？建议直接在greasyfork上点安装，greasyfork应该会带编码类型所以一般不会乱码，这仓库里的脚本应该都是utf-8编码的，直接在仓库里点raw安装应该也没事，如果下载之后从本地拉到浏览器里安装可能会乱码。如果直接安装还是乱码那就点开tampermokney编辑脚本，把正确的脚本内容直接复制过去保存吧

**Comment by Evansmay** [comment]
谢谢回复 已解决！
