### ISSUE TITLE
html5视频截图器，建议下载下来的图片名按照时间戳设置

### ISSUE THREAD

**Issue by KANA108** [indefined/UserScripts#19]
html5视频截图器，建议下载下来的图片名按照时间戳设置

**Comment by indefined** [comment]
感觉并不是所有人都需要这个功能，我在设置里加个选项吧

**Comment by KANA108** [comment]
> 感觉并不是所有人都需要这个功能，我在设置里加个选项吧

ok,辛苦了，因为默认的下载名我放到markdown就出了问题，所以才提这个建议的
