### ISSUE TITLE
HTML5视频截图器点击直接下载截图（快捷键q）却打开了新窗口没有下载

### ISSUE THREAD

**Issue by KANA108** [indefined/UserScripts#20]
HTML5视频截图器点击直接下载截图（快捷键q）却打开了新窗口没有下载

**Comment by KANA108** [comment]
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**Comment by indefined** [comment]
使用说明里有写了
`直接下载截图并不一定对所有视频和浏览器有效，有时可能和点截图按钮效果一样，甚至可能点了完全没有反应`
目前这个脚本因为脏画布污染限制并没有办法对所有视频截图直接下载，如果视频的来源和正在播放的网站不一样，浏览器会认为这个视频内容是不受信任的，从这个视频里取出的内容会被认为被污染了不安全只允许用来显示不允许脚本拿出来用，所以没办法直接下载只能自己在画面上右键另存，甚至可能另存也会失败。
虽然理论上应该可以挟持更改播放器的跨域属性，但是不知道泛用性如何，而且这个脚本在所有网站运行但是整体使用率并不高，挟持所有播放器也不知道会不会有什么副作用。这个问题等我再找时间试验一下吧，但是并没有办法保证什么时候能完成，也许几天也许几个月甚至不会去搞，这个脚本的复杂度已经远超当初设计了，再加功能估计需要重构一下不然很乱

**Comment by KANA108** [comment]
> 使用说明里有写了
> `直接下载截图并不一定对所有视频和浏览器有效，有时可能和点截图按钮效果一样，甚至可能点了完全没有反应`
> 目前这个脚本因为脏画布污染限制并没有办法对所有视频截图直接下载，如果视频的来源和正在播放的网站不一样，浏览器会认为这个视频内容是不受信任的，从这个视频里取出的内容会被认为被污染了不安全只允许用来显示不允许脚本拿出来用，所以没办法直接下载只能自己在画面上右键另存，甚至可能另存也会失败。
> 虽然理论上应该可以挟持更改播放器的跨域属性，但是不知道泛用性如何，而且这个脚本在所有网站运行但是整体使用率并不高，挟持所有播放器也不知道会不会有什么副作用。这个问题等我再找时间试验一下吧，但是并没有办法保证什么时候能完成，也许几天也许几个月甚至不会去搞，这个脚本的复杂度已经远超当初设计了，再加功能估计需要重构一下不然很乱

好的，没问题

**Comment by indefined** [comment]
上个版本在设置中增加了一个匿名跨域的选项，实测作用十分差，我只测出一两个网站有些作用，其它甚至有些视频无法播放……总而言之更新推上去了，对于无法截图的网站就试试勾上看能不能用吧，不能再关掉大概也没什么好办法
这个issue暂时挂起关了吧，应该暂时也不会去优化它，这脚本的可开发潜力实在不高一时半会应该不会真正对它有大型重构了，等哪天真的心血来潮再挖出来吧……
