### ISSUE TITLE
html视频截图器，建议添加画中画播放（小窗播放）

### ISSUE THREAD

**Issue by KANA108** [indefined/UserScripts#21]
html视频截图器，建议添加画中画播放（小窗播放）
![2020-03-20_141951](https://user-images.githubusercontent.com/55820158/77140882-f88f7f00-6ab5-11ea-98fc-358c4952d03c.png)

**Comment by indefined** [comment]
没有增加类似功能的计划，画中画功能的独立脚本应该很多人写了，把这个脚本做成多功能播放器外壳并不实际，目前应该只会发展截图相关的功能。 close.

shiny <notifications@github.com> 于2020年3月20日周五 下午2:20写道：
