### ISSUE TITLE
bilibili直播间工具 错位

### ISSUE THREAD

**Issue by LOVE-END** [indefined/UserScripts#24]
勋章，头衔切换无法使用，出现错位。
送礼辣条界面有点问题

![0011](https://user-images.githubusercontent.com/61007431/78466469-10146c00-7734-11ea-9ccb-1b190abfed3e.png)

希望可以修复
感谢大大

**Comment by indefined** [comment]
具体在哪个房间？使用什么浏览器和脚本管理器？勋章和头衔我这边并没有问题，道具包裹里的样式是脚本里替换回旧版的，不喜欢的话下个版本我可以写个设置自己关掉

**Comment by indefined** [comment]
道具包裹里的样式已经加入开关，设置开关的位置在播放器里可以去看功能预览的第一张图示意自己改。
你截图的那个错位图标不是勋章和头衔的切换开关，勋章和头衔的功能是原有的“勋”和“衔”按钮，启用后会覆盖掉原有的功能，那个错位的图标是旧版礼物，历史遗留的没用旧功能，不想看到的话也可以在设置里关掉。因为上次更新动了些手脚导致无法打开，现在应该已经能用了，不过按理打不开应该也不会错位，如果这次更新之后仍然不能用或者错位说明一下使用的浏览器和脚本管理器，以及按F12看控制台是否有错误报告

**Comment by LOVE-END** [comment]
不用关掉，很好看。现在又可以用啦，可能是因为beta版的Chrome不稳定叭。用的是稳定版的Tampermonkey。全屏发弹幕的功能超级好用，感谢大大做出那么好的脚本。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "indefined"<notifications@github.com&gt;; 
发送时间: 2020年4月5日(星期天) 晚上7:08
收件人: "indefined/UserScripts"<UserScripts@noreply.github.com&gt;; 
抄送: "&amp;#x1D17;"<3234799213@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [indefined/UserScripts] bilibili直播间工具 (#24)





 
具体在哪个房间？使用什么浏览器和脚本管理器？勋章和头衔我这边并没有问题，道具包裹里的样式是脚本里替换回旧版的，不喜欢的话下个版本我可以写个设置自己关掉

**Comment by LOVE-END** [comment]
可以完美运行啦，嘻嘻嘻






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "indefined"<notifications@github.com&gt;; 
发送时间: 2020年4月5日(星期天) 晚上7:55
收件人: "indefined/UserScripts"<UserScripts@noreply.github.com&gt;; 
抄送: "&amp;#x1D17;"<3234799213@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [indefined/UserScripts] bilibili直播间工具 (#24)





 
道具包裹里的样式已经加入开关，设置开关的位置在播放器里可以去看功能预览的第一张图示意自己改。
 你截图的那个错位图标不是勋章和头衔的切换开关，勋章和头衔的功能是原有的“勋”和“衔”按钮，启用后会覆盖掉原有的功能，那个错位的图标是旧版礼物，历史遗留的没用旧功能，不想看到的话也可以在设置里关掉。因为上次更新动了些手脚导致无法打开，现在应该已经能用了，不过按理打不开应该也不会错位，如果这次更新之后仍然不能用或者错位说明一下使用的浏览器和脚本管理器，以及按F12看控制台是否有错误报告
 
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
