### ISSUE TITLE
B站APP首页 最右边一列视频不在正确的位置

### ISSUE THREAD

**Issue by wulifuji** [indefined/UserScripts#25]
## 原因疑为列间距过大 ，最右一列【×】卡在全站排行里

**Comment by indefined** [comment]
请说明使用的浏览器和分辨率，以及设置中有无开启不显示滚动条，如果有截图就更好了。

B站的首页是自适应弹性布局的，会自己根据你的分辨率调整列数，我并没有那么多条件可以每个分辨率全测一遍，顺便如果现在出问题的话你说的应该是新版首页，新版的间距也是自动调整的，我并没有指定它的宽度，如果超过了宽度应该会自动被挤到下一行才对

**Comment by wulifuji** [comment]
应该更正一下：在视频被（被设定的）数量正好并不需要滚动的情况下，关闭显示滚动条，视频贴图会向右填充，最右边的一列就压在了下面；而打开设置里的显示滚动条，滚动条实际上不会出现，但会占据那个位置，贴图就不会错误地向右填充了，总之是个特殊情况……

**Comment by indefined** [comment]
重复一下你的浏览器和分辨率，我有空再去测试一下
