### ISSUE TITLE
[bilibiliLive] 渐变灰显示不正常闪烁

### ISSUE THREAD

**Issue by slinar** [indefined/UserScripts#27]
使用chrome打开bili直播间 灰色渐变显示会有问题 并且舰长列表动画触发的时候会闪烁 如下图

请附带说明：
1. 使用了什么浏览器
    chrome 81.0.4044.129
2. 使用了什么脚本管理器
    Tampermonkey 4.10
3. 如果这个问题和显示错位有关，请说明你使用的浏览器分辨率
4. 其它你有头绪的线索

**截图**
![Snipaste_2020-05-05_22-27-33](https://user-images.githubusercontent.com/41759351/81078629-0fcce380-8f21-11ea-8b60-cd2957954030.png)
左边是加载脚本,看上去像渐变灰溢出视频的范围了  右边是没有加载脚本正常

**错误报告**

<details>
<summary>浏览器控制台错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
理论上确实会有这个现象，之前把礼物包裹放进网页全屏播放器之后悬停的赠送礼物面板会超出播放器范围，所以我加了个样式允许播放器里面的内容溢出显示，加的时候就猜到会有其它溢出的可能现象，不过一直没有收到报告我也就忘了。我试了一下现在播放器里的礼物面板已经不会超出播放器范围了所以这个样式也可以去掉了，不过我这边找了几个直播间似乎看不到这个现象所以也不知道你那边是不是这个原因。总之我先推个更新上去看看，如果没有解决请继续回复我再找找别的原因

**Comment by slinar** [comment]
更新完好像没问题了 这个问题只会在用手机直播的时候网页观看才会出现  这个小脚本非常方便 感谢
