### ISSUE TITLE
关于使用硬币购买勋章的问题

### ISSUE THREAD

**Issue by URGERKING** [indefined/UserScripts#28]
请问如果一个Up主没有发布满十个视频依旧能点击购买并成功吗?亦或是显示失败?目前我不敢直接点击..
[一个Up主的例子](https://live.bilibili.com/21438956)

**Comment by URGERKING** [comment]
补充:如果失败的话会扣除我的硬币吗?

**Comment by indefined** [comment]
可以购买成功，这个功能并不会给UP主的视频投币，它只是单纯的用硬币购买勋章而已，所以和UP主有没有视频以及你曾经有没有给UP主投过硬币都没关系，固定消耗20硬币获得勋章和100点亲密度。
理论上，即使UP主没有勋章，或者说将来这个功能失效了，只要没有购买成功就不会扣除硬币，不过实际B站将来关闭这个功能之后会怎么处理我也无法保证，我只能说目前我试了如果没购买成功是不会扣的，以后的事我也不清楚，毕竟我也无法每次都替你购买一个试试
