### ISSUE TITLE
[H5截图]跳帧无法暂停&功能建议

### ISSUE THREAD

**Issue by sojey** [indefined/UserScripts#30]
详细描述你遇到的问题

请附带说明：
1. 使用了什么浏览器 EDGE beta
2. 使用了什么脚本管理器 Tampermonkey 
3. 如果这个问题和显示错位有关，请说明你使用的浏览器分辨率 2560*1440
4. 其它你有头绪的线索

https://www.agefans.tv/play/20160005?playid=3_18
该网页的视频前后跳帧之后，不能暂停。

另还有一些问题：
1、HTML5播放器增强版最近无法截图，作者称不能支持。于是用起这个之前收藏的脚本。
虽然可以解决截图问题，但部分快捷键无法支持 Ctrl Shift Alt 单个或多个组合，确实很容易在YouTube等部分有默认热键的网页中产生冲突。比如f的跳帧，就和YouTube全屏冲突，被迫需要改键。若是能直接覆盖YouTube热键那多好，因为PotPlayer，和之前提到的脚本播放器，都是df前后跳帧。一致性更好。

2、面板如果能收起，透明化在某处那就更好了。 比如  网页限制解除（改）就非常好的在所有页面左上角透明化，鼠标悬停激活。

3、← →跳时间如果能前跳10秒，后跳5秒，或者自定义，或者追加 Ctrl 或 Shift+→的方式自定义跳转时间。那就更好了。

**Comment by indefined** [comment]
跳帧问题确实是个问题，但是目前这个脚本并没有解决方案，脚本描述的问题说明里也有写，某些播放器改变时间之后会自动播放所以逐帧可能无效。这个问题我看过你说的那个脚本处理方案是挟持播放器原有的事件，但是这个脚本目前并没有计划做这么复杂，或者说以这个脚本目前乱七八糟的结构并没有办法做这么复杂，一旦挟持可能会有更多的问题发生，而且即使这么做了也不一定能解决所有网站问题

关于你说的其它几个建议：
1. 网页原有快捷键可以简单尝试覆盖，但是不一定会生效，比如B站的F全屏可以阻止，而Youtube就阻止不了，任意快捷键组合也可以做，但是应该也不会带来太大体验改善，下次更新我可以加入相应的选项设置功能
2. 没有打算做，考虑到这个脚本的实际使用率加入的冲突概率应该会大于实用性
3. 目前也没有加入的计划，主要是设置面板会很混乱，并且也不是这脚本主要功能

关于这个脚本最初就只是想尽可能避免侵入的情况下最小操作实现通用截图，虽然随着各种增补现在脚本变得臃肿起来也多多少少有些侵入了，但是要把这个脚本当作通用播放器控制外壳那它显然太菜了，因为各种因素限制下它实际通用性并不强，从结构和本人能力上来说这个脚本的可扩展性也实在不高，除非真的哪天把它重写成多功能通用播放器外壳了否则应该不会加入其它播放器控制的增强，原有的功能问题除非有简单的非侵入通用解决方案否则也会保持不能做就不做的惰性应对

**Comment by indefined** [comment]
快捷键相关设置选项已添加，逐帧暂停目前测试了一个比较简单的挟持方法，可能会有些用处但是实际适用性有多大就不知道了，其它功能暂时应该不做了，短时间内应该就这样了吧，除非是这次带来新BUG否则这个话题就挂起等到哪天真的心血来潮重做再挖出来，当然也可能永远也不会被挖出来
