### ISSUE TITLE
[APP首页推荐设置] 获取授权错误

### ISSUE THREAD

**Issue by wulifuji** [indefined/UserScripts#31]
截图下，获取错误了，试了几次都不行
![image](https://user-images.githubusercontent.com/61496038/84342522-5674c400-abd8-11ea-8f53-c3bd2fba8473.png)

**Comment by indefined** [comment]
看上去授权接口直接挂了，B站直接把用户反馈论坛关掉了……昨天有人反馈被拦截但我这边还能用，今天我这边也用不了了。我先折腾一下吧估计和上次接口挂掉一样短时间内是无法解决的，不想做输入帐号密码的登录接口，没找到替代接口的话估计会停更这个脚本
