### ISSUE TITLE
[bilibili网页端首页增加APP首页推荐] 在chrome浏览器110%缩放下显示不正常

### ISSUE THREAD

**Issue by talking-toaster** [indefined/UserScripts#32]
bilibili网页端首页增加APP首页推荐脚本 在chrome浏览器110%缩放下显示不正常

1. 使用了什么浏览器 Google Chrome 版本 81.0.4044.129（正式版本） （64 位）
2. 使用了什么脚本管理器：Tampermonkey
3. 如果这个问题和显示错位有关，请说明你使用的浏览器分辨率：110%
4. 其它你有头绪的线索
![error1](https://user-images.githubusercontent.com/49156890/84968611-84628700-b149-11ea-81d5-e158d513ac22.png)
可以看到左边下方露出了下面视频的一部分，右侧全站排行，第一位的高度有问题，“日”“周”等字缺失最上面的“—”
![error2](https://user-images.githubusercontent.com/49156890/84968620-89bfd180-b149-11ea-9b69-963f2fc6611a.png)

**错误报告**

<details>
<summary>浏览器控制台错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
右边的排行榜是旧版直接搬过来的样式，确实有些问题可以修一下。左边的推荐内容，试了一下并没有办法安逸修复，和高度计算没有关系，因为在缩放条件下，页面元素乘上一定系数之后确实会出现多几像素少几像素的不整齐情况。有个比较歪的方法减掉一行间隔高度可能可以缓冲掉几像素的偏差，但是对于那些设置了内容和高度一样的人来说会出现不该出现的滚动条。总之我在设置里加了个选项，更新之后可以试一下，不过最好反馈一下使用效果，因为我并不确定这个东西的适应性以及要不要保留这个选项

**Comment by talking-toaster** [comment]
更新最新0.6.8版本已修复右侧全站排行显示不全问题，开启设置`减去高度间隔`完美消除视频推荐下方黑边，在各种缩放下未发现显示问题，希望可以保留这个设置项

**Comment by indefined** [comment]
那这个反馈就先关了，有相同问题可以继续回复
