### ISSUE TITLE
[HTML5视频截图]截图并下载功能在多个网站不能完整工作

### ISSUE THREAD

**Issue by sojey** [indefined/UserScripts#33]
详细描述你遇到的问题

请附带说明：
1. EDGE浏览器beta最新版
2. tampermonkey脚本管理器
3. win10 x64正版 最新版 2560*1440 125%图表放大
4. 最近10天左右，http://agefans.top/acg/36275/13.html 以及 https://www.agefans.tv/play/20130012?playid=3_9 基本上agefans的多数域名下的 ckplayer 使用 视频截图并下载功能，在全屏、网页等所有方式，都无法完整执行，只能新建窗口显示截图。

现在市面上能做到较好兼容性的视频截图工具，也只有您这个脚本了。但是ckplayer到底是何方神圣，为什么总会出现各类兼容性问题。而Chrome内核的除国产流氓浏览器外，没有一款对快速保存图片有较好优化的。这就是很讨厌的地方。

希望能够尽快修正。

从前用的HTML5播放器增强版的脚本，称因为技术原因无法兼容ckplayer的视频截图，后发现这个脚本仍然可以。但最近又出现问题了。真可惜。

**截图**

**错误报告**

<details>
<summary>浏览器控制台错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
简介说明了有简单写了，下次我还是写得仔细一点吧。简单来说问题并不是播放器造成的，是因为网站跨域加载的该网站域名之外的视频被浏览器认为是不安全所以拦截了脚本对视频内容的访问。

很多小型视频网站他们里面播放的视频都不是自己的，可能是第三方网站提供的，这些视频基本都无法直接下载截图，虽然有办法可以尝试绕过这个限制，但是通用性不高而且可能造成更多问题。脚本设置里提供了一个“匿名跨域”的选项，对于无法截图的网站你可以尝试勾选上然后保存为这个网站专用配置然后刷新网页看看有没有用。

注意如果你在截图工具栏上看到的视频前面带有"0-0-1-0"之类的前缀那么你保存的网站也必须和这个前缀相同。如果勾选了也没有用那么你应该删掉这个配置，跨域问题处理起来很棘手这个脚本只是简单尝试了一下能不能用罢了，动态加载的内容是不会被处理到的，同时有些网站匿名之后是获取不到视频的。你提供的两个网址第二个可以通过这个方法兼容，第一个就没办法。对于不允许跨域的视频来说这是浏览器硬性的限制基本不可能解决，对于能允许跨域的，在找到更简单高效的处理方法之前应该也不会增加兼容，这对于正常的网页访问会存在副作用不符合这个脚本不用就不干扰的逻辑
