### ISSUE TITLE
[网易CC直播净化] 去除logo水印功能不能用

### ISSUE THREAD

**Issue by programmerZe** [indefined/UserScripts#34]
1. 脚本名称：网易CC直播净化

2. 脚本使用环境：Win10 Edge83.0.478.58 Tampermonkey4.10

3. 问题详细描述：之前使用正常，今天logo无法去除，重复打开关闭没效果，刷新页面也没效果
![image](https://user-images.githubusercontent.com/32977308/86927776-55e33500-c166-11ea-82d4-34926502581e.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
已修复

**Comment by programmerZe** [comment]
非常感谢！
