### ISSUE TITLE
[B站网页端添加APP首页推荐] 无法获取授权

### ISSUE THREAD

**Issue by anpoz** [indefined/UserScripts#35]
1. 脚本名称：
B站网页端添加APP首页推荐

2. 脚本使用环境：

win10 2004 chrome83 Tampermonkey4.10 1920x1080 100%

3. 问题详细描述：

点击按钮无法获取授权

![)@7 6}BV@(~VL7K3{NF{)R9](https://user-images.githubusercontent.com/2825342/87222569-3555ed80-c3a7-11ea-9576-420682f890de.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

获取授权失败:获取授权错误 {msg: undefined, toString: ƒ}msg: undefinedtoString: ()=>'获取授权错误'__proto__: Object
toast @ userscript.html?name=bilibili%E7%BD%91%E9%A1%B5%E7%AB%AF%E6%B7%BB%E5%8A%A0APP%E9%A6%96%E9%A1%B5%E6%8E%A8%E8%8D%90.user.js&id=db63abad-6d79-4893-a517-4a21eadeaa3c:961
eval @ userscript.html?name=bilibili%E7%BD%91%E9%A1%B5%E7%AB%AF%E6%B7%BB%E5%8A%A0APP%E9%A6%96%E9%A1%B5%E6%8E%A8%E8%8D%90.user.js&id=db63abad-6d79-4893-a517-4a21eadeaa3c:888
Promise.catch (async)
handleKey @ userscript.html?name=bilibili%E7%BD%91%E9%A1%B5%E7%AB%AF%E6%B7%BB%E5%8A%A0APP%E9%A6%96%E9%A1%B5%E6%8E%A8%E8%8D%90.user.js&id=db63abad-6d79-4893-a517-4a21eadeaa3c:886
onclick @ userscript.html?name=bilibili%E7%BD%91%E9%A1%B5%E7%AB%AF%E6%B7%BB%E5%8A%A0APP%E9%A6%96%E9%A1%B5%E6%8E%A8%E8%8D%90.user.js&id=db63abad-6d79-4893-a517-4a21eadeaa3c:829
</code>
</pre>
</details>

**Comment by indefined** [comment]
脚本版本是最新的吗？这个问题在上一个版本遇到过，是授权接口失效了导致的，最新版应该是已经修复了，如果确定最新的重试也一样结果的话我考虑推一个没有功能更新的版本，需要你更新之后再反馈错误报告以便排错，因为目前的代码里写的错误捕捉信息太少错误报告无法定位到具体的问题

**Comment by anpoz** [comment]
> 脚本版本是最新的吗？这个问题在上一个版本遇到过，是授权接口失效了导致的，最新版应该是已经修复了，如果确定最新的重试也一样结果的话我考虑推一个没有功能更新的版本，需要你更新之后再反馈错误报告以便排错，因为目前的代码里写的错误捕捉信息太少错误报告无法定位到具体的问题

刚找到发布页手动更新了，问题解决了。这tampermonkey竟然不会自动更新有点小坑...

**Comment by indefined** [comment]
那这个反馈我就关了
