### ISSUE TITLE
[bilibili网页端添加APP首页推荐] 加载更多每次只加载10条新视频

### ISSUE THREAD

**Issue by maweihao999** [indefined/UserScripts#36]
1. 脚本名称：bilibili网页端添加APP首页推荐

2. 脚本使用环境：Win10 Chrome83 Tampermonkey4.1

3. 问题详细描述：点击加载更多每次只加载10条新视频。详细设置如下：保存推荐数量0，页面显示限制18，自动刷新页数2，显示推荐高度3。在这种设置下，每次点击加载更多都有8条视频不会被更新，只更新10条视频，如果设置页面显示限制为20，则有10条视频不会被更新，以此类推。

![QQ截图20200712233236](https://user-images.githubusercontent.com/8280337/87250727-86dea500-c499-11ea-9c79-338c628e144b.jpg)
![QQ截图20200712233246](https://user-images.githubusercontent.com/8280337/87250728-87773b80-c499-11ea-867a-8143329f785b.jpg)
第一张图里的第2-10个视频在第二张图中显示为第13-20个视频。

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
嗯……这个应该说设计上就是这样的，那个自动刷新页数原本就是设计只是加载时会自动刷新那么多页的，手动点击的话每次还是只加载一页。因为我自己一直只用一页所以也没考虑这么多。按照你的反馈个人觉得还是增加一个手动刷新页数的设置项吧，把手动刷新改成和自动刷新一样可能会导致其他用习惯的人反而不适用了，虽然我也不知道你们大多数人是怎么设置的……

**Comment by maweihao999** [comment]
就我个人的使用习惯而言，我是会一直手动刷看有没有自己喜欢的视频，有喜欢的就先后台打开再继续刷，攒够几个视频再一起看。

另外我之前也设置过只显示10条视频，这样就不会存在有视频不会被刷新的问题了，但是在我的分辨率下（3840*2160 win10全局200%缩放），一行是会显示6个视频的，这样就变成了两行6+4的排列很不美观，网页110%缩放后会显示为1行5个，但这样字体对我来说又显得太大了。

**Comment by indefined** [comment]
已更新，可以试试，有BUG可以在下面反馈。奇怪的选项越来越多了orz

**Comment by maweihao999** [comment]
感谢！！！作者效率这么高，感动
