### ISSUE TITLE
[BLCC]旧版播放器默认数据

### ISSUE THREAD

**Issue by MotooriKashin** [indefined/UserScripts#38]
1. 脚本名称：Bilibili CC字幕工具

2. 脚本使用环境：Win8 Chrome 84.0.4147.135 Tampermonkey 4.11.6118

3. 问题详细描述：
> 如果以前没有在新版页面使用过CC字幕会自动生成一个默认设置，有没有效果就不知道了

亲测是无效的，会报错`CC字幕助手配置失败:SyntaxError: Unexpected token u in JSON at position 0`  
大概分析了一下，不管到底使用旧版播放器多久了，如果没有调整过旧版播放器的设置，一直以默认设置使用的话，播放器根本不会在LocalStorage中生成名为`bilibili_player_settings`的键值，我猜想脚本可能会判断`bilibili_player_settings`值存在才“生成一个默认设置”，`bilibili_player_settings`值不存在的话就永远不会生成，所以将一直报错下去，除非调整过播放器的设置或者去新版页面使用一次。  

<details>
<summary>错误报告</summary>
<pre>
<code>

userscript.html?name=Bilibili%20CC%E5%AD%97%E5%B9%95%E5%B7%A5%E5%85%B7.user.js&id=90c2993a-5cf2-4e5f-bbe9-9f3d3efb398b:861 CC字幕助手配置失败 SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.init (userscript.html?name=Bilibili%20CC%E5%AD%97%E5%B9%95%E5%B7%A5%E5%85%B7.user.js&id=90c2993a-5cf2-4e5f-bbe9-9f3d3efb398b:725)
    at eval (userscript.html?name=Bilibili%20CC%E5%AD%97%E5%B9%95%E5%B7%A5%E5%85%B7.user.js&id=90c2993a-5cf2-4e5f-bbe9-9f3d3efb398b:932)
toast @ userscript.html?name=Bilibili%20CC%E5%AD%97%E5%B9%95%E5%B7%A5%E5%85%B7.user.js&id=90c2993a-5cf2-4e5f-bbe9-9f3d3efb398b:861

</code>
</pre>
</details>

**Comment by indefined** [comment]
感谢反馈，加了个捕捉判断，现在大概也许应该没问题了……

**Comment by MotooriKashin** [comment]
感谢修复！旧版播放器毕竟已成过去，所以一直没敢提issue  
可我习惯在隐身模式下调试，每次console里必定有CC字幕的报错  
强迫症今天终于忍不下去了……

再次感谢专门为旧版播放器维护这个功能
