### ISSUE TITLE
[B站旧版播放页] 评论区时间轴跳转部分失效

### ISSUE THREAD

**Issue by iamapig120** [indefined/UserScripts#40]
1. 脚本名称：B站旧版播放页

2. 脚本使用环境：Win10 Chrome 当前最新版 1080P 100%缩放

3. 问题详细描述：
评论区时间轴跳转部分失效
可以参考
https://www.bilibili.com/video/av415232058?

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
这个仓库里存的那个旧播放页脚本基本已经弃用了，因为我自己也不使用所以应该也不维护了，你可以看一下这个[Bilibili 旧播放页](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5
) 写得应该挺完善的

**Comment by iamapig120** [comment]
确实是这个油猴库的响应功能无效，另外似乎左右快进快推快捷键这两天也失效了

**Comment by indefined** [comment]
我理解是我的脚本有问题，不过那个脚本已经很久没维护过了，除了你说的可能还有更多问题，我自己也不使用，如果有相应需求的话建议使用上面那个链接的版本，那个写得更完善也可以自己开关相应的功能，我这边应该不会维护这个旧脚本了，抱歉
