### ISSUE TITLE
[bilibili网页端添加APP首页推荐]启用后全站排行“昨天”标签下的数据一直都是旧数据

### ISSUE THREAD

**Issue by anpoz** [indefined/UserScripts#42]
1. 脚本名称：

bilibili网页端添加APP首页推荐 0.6.10

2. 脚本使用环境：

win10 edge86.0.622.69 Tampermonkey4.11

3. 问题详细描述：

启用后全站排行“昨天”标签下的数据一直都是旧数据

![屏幕截图 2020-11-19 102456](https://user-images.githubusercontent.com/2825342/99613138-fb31e200-2a51-11eb-93d2-ecf1bff81c88.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
似乎确实不更新了，有注意这个问题多久了吗？B站的全站排行榜已经不显示日期很久了，这个脚本里用的是很久以前的旧版接口，所以B站关掉了数据更新也是可能的，等观察几天看看其它日期选项是不是还更新吧，我去找找有没有其它还能用的旧接口备份，如果没有的话可能要删掉这些选项，毕竟用的还是B站的接口B站不更新我这边也没办法

**Comment by anpoz** [comment]
> 似乎确实不更新了，有注意这个问题多久了吗？B站的全站排行榜已经不显示日期很久了，这个脚本里用的是很久以前的旧版接口，所以B站关掉了数据更新也是可能的，等观察几天看看其它日期选项是不是还更新吧，我去找找有没有其它还能用的旧接口备份，如果没有的话可能要删掉这些选项，毕竟用的还是B站的接口B站不更新我这边也没办法

一个多月了

**Comment by indefined** [comment]
观察了一天所有日期选项基本都是无效的，只有3天全部排行和当前的全部排行是一致的，找了一圈所有全站排行接口基本都失效了，连旧版APP也只有一个全站排行选项，B站应该彻底不提供这方面数据了。目前还有一个近期投稿排行接口是有效的，暂时改为近期投稿排行，可能也用不了多久，失效了再说吧。这个反馈暂时先开着看看，过段时间如果没问题再说
