### ISSUE TITLE
使用Bilibili CC字幕工具 0.5.17.2无法下载初音未来魔法未来2020演唱会字幕

### ISSUE THREAD

**Issue by YFTX2015** [indefined/UserScripts#44]
1. 脚本名称：
Bilibili CC字幕工具 0.5.17.2

2. 脚本使用环境：
win10 Google Chrome 87.0.4280.66

Tampermonkey Beta 4.12.6121

3. 问题详细描述：
![屏幕截图(1)](https://user-images.githubusercontent.com/12757305/100653770-dc9de600-3383-11eb-8d52-edb72baf2631.png)
![屏幕截图(2)](https://user-images.githubusercontent.com/12757305/100653778-df98d680-3383-11eb-9d18-8f7c339615f2.png)
![屏幕截图(3)](https://user-images.githubusercontent.com/12757305/100653780-e0316d00-3383-11eb-80e0-973586306d83.png)
![屏幕截图(4)](https://user-images.githubusercontent.com/12757305/100653783-e1629a00-3383-11eb-9081-d7b6fba7bbc2.png)
![屏幕截图(5)](https://user-images.githubusercontent.com/12757305/100653788-e1fb3080-3383-11eb-8df4-770191c21ca1.png)
就算重新加载视频，CC图标仍然划叉，字幕下拉框无法显示字幕语种，下载按钮呈现灰色，无法下载字幕。根据UP主的说法，“CC字幕正在施工中” 无法确定视频底端的字幕是否为CC字幕。脚本显示的内容也看不出个所以然。

**Comment by indefined** [comment]
现在这个视频没有CC字幕，底部的歌词是弹幕，就是评论里说了“在此之前底部的歌词弹幕会进行保护”，这个脚本是不处理弹幕内容的，既然官方说了CC字幕在施工那等段时间他会上传的，到时候有字幕了应该就是可以下载的

**Comment by indefined** [comment]
现在这个视频已经有字幕了，没什么情况这反馈我就关了

**Comment by YFTX2015** [comment]
嗯，可以下了
