### ISSUE TITLE
[bilibili网页端添加app首页推荐] 全站排行是空白的

### ISSUE THREAD

**Issue by lamcodes** [indefined/UserScripts#45]
1. 脚本名称：

bilibili网页端添加app首页推荐 0.6.11
2. 脚本使用环境：

win10  Microsoft Edge 版本 87.0.664.52 
3. 问题详细描述：

全站排行是空白的。下有截图。

![image](https://user-images.githubusercontent.com/40131457/100979845-4fbf7c00-357f-11eb-924c-fe8944f74382.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by lamcodes** [comment]
![image](https://user-images.githubusercontent.com/40131457/100979812-40d8c980-357f-11eb-8064-8a07a81640ef.png)

**Comment by indefined** [comment]
旧版排行接口失效了，换用了新版排行，但是新版没有日期了

**Comment by lamcodes** [comment]
那样如何设置才能显示这个排行呢？

**Comment by indefined** [comment]
更新一下就好了，不过发现更新后有新问题，等我再修一下再更新吧

**Comment by indefined** [comment]
修好了，可以去脚本发布页或者在脚本管理器里更新一下脚本

**Comment by lamcodes** [comment]
好的，谢谢。
