### ISSUE TITLE
[bilibili直播间工具] B站新版面无法支持

### ISSUE THREAD

**Issue by Andy8r0X** [indefined/UserScripts#46]
1. 脚本名称：bilibili直播间工具 0.5.26

2. 脚本使用环境：Windows 7 / Chrome 87.0.4280.88 / Tampermonkey 4.11

3. 问题详细描述：B站介面改版的新版样式，工具无法支持
![2020-12-16_160155](https://user-images.githubusercontent.com/2507836/102321168-3f17f880-3fb8-11eb-8e25-a83e78278e21.png)

**Comment by indefined** [comment]
总之目前先修了，不知道 还会不会有什么更改或者哪里有错误，有错误再说
