### ISSUE TITLE
[bilibili直播间工具] 新界面无法隐藏礼物栏

### ISSUE THREAD

**Issue by choyike** [indefined/UserScripts#47]
1. 脚本名称：bilibili直播间工具 0.5.31

2. 脚本使用环境：win10 Chrome87  Tampermonkey4.11 

3. 问题详细描述：直播间界面的礼物栏在半屏状态下无法隐藏了。

![QQ截图20201226192529](https://user-images.githubusercontent.com/32677144/103150590-88cec300-47b0-11eb-9447-45ae75ff409b.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
已更新，大概修好了
