### ISSUE TITLE
[bilibili网页端添加APP首页推荐] 偶尔刷新没反应而且在刷新几次后经常会有大量视频重复

### ISSUE THREAD

**Issue by winmerdx** [indefined/UserScripts#48]
1. 脚本名称：
bilibili网页端添加APP首页推荐 0.6.12.2
2. 脚本使用环境：
Win10 20H2 
360急速浏览器 版本号:12.0.1344.0 内核版本:78.0.3904.108 
Tampermonkey4.11

3. 问题详细描述：
有时候点击加载更多一直没反应，然后就是可能刷新一次都会有相同的视频，在多次刷新时候会有大量的视频重复。
![QQ截图20210105112605](https://user-images.githubusercontent.com/62535410/103603137-d4b7ff80-4f48-11eb-8e84-d5f0a53976ac.png)

**Comment by indefined** [comment]
是点了完全没反应还是一直正在加载或者正在加载过后消失了，如果有错误的话按F12看有没有[bilibili网页端添加APP首页推荐]相关的红色错误报告，没有错误的话这边也没办法修，我这边并没有遇到无法刷新情况。至于数据说明里面已经说了，这是B站自己提供的我也不知道他会给什么，重复的话你可以点不喜欢，点了有没有用我也不知道

**Comment by winmerdx** [comment]
![image](https://user-images.githubusercontent.com/62535410/103604702-da174900-4f4c-11eb-962b-89957102e37d.png)
这个是所有的

**Comment by indefined** [comment]
里面没有这个脚本的相关错误。正常点加载更多会在顶部出现正在加载的提示，加载完新推荐会消失掉，如果是常规的错误信息的话也会显示在那条正在加载那里。我看了一下逻辑似乎也没什么其它能错误的情形。从描述猜的可能情况，要么点击完一直显示正在加载，那可能是网络超时了一直没有回应，无视它重新加载一次可能有效？要么显示正在加载然后消失掉了但是没有显示新推荐，那可能是B站的服务器没有返回任何内容，说明B站可能打算废掉旧版接口了，我这边还没有遇到相同情况可以调试，暂时先观察一段时间看看有没有更多情报吧
