### ISSUE TITLE
[BLCC] 番剧页面配置失败

### ISSUE THREAD

**Issue by MotooriKashin** [indefined/UserScripts#49]
1. 脚本名称：Bilibili CC字幕工具

2. 脚本使用环境：Win8 Chrome87 Tampermonkey4.1

3. 问题详细描述： 进入任意番剧页面报错

![2021-01-14_165516](https://user-images.githubusercontent.com/60416767/104567604-ee182480-5689-11eb-9a04-e7e9aed5acc7.png)  
![2021-01-14_165247](https://user-images.githubusercontent.com/60416767/104567535-e193cc00-5689-11eb-89c5-992629315185.png)  
调查发页面所有xhr同由同一脚本发出，`v=20210114`似乎昭示着这是今天刚引入的脚本  
![2021-01-14_165343](https://user-images.githubusercontent.com/60416767/104567906-4e0ecb00-568a-11eb-95ad-a9fc651488c0.png)  
进入sources页面发现`open`、`send`等方法似乎被hook了  
![2021-01-14_165433](https://user-images.githubusercontent.com/60416767/104568053-86aea480-568a-11eb-845d-94482f349a55.png)  
只在新版番剧页面出现，旧版及av页等无异常，不过每打开一次番剧都报一次错对于安装了字幕脚本的用户而言应该不堪其扰吧。

ps：这么专对番剧页面，而且又涉及xhr hook，个人不禁联想到官方这几天对于区域限制番剧的一系列操作……当中应该有联系吧。万幸暂时与旧版页面无碍就是了。

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by MotooriKashin** [comment]
我是随便点进任何一个番剧都是，比如冰菓，比如新番蜘蛛子

**Comment by MotooriKashin** [comment]
难道这个脚本是灰度测试？附上该脚本链接https://s1.hdslb.com/bfs/static/ogv/fe/iris.min.js?v=20210114.1

**Comment by indefined** [comment]
发现问题了，是我脚本加载的比较快没有被hook到，加载完再点别的就出错了。你那边每个页面新开都会出错吗？如果没法确认脚本运行时机的话似乎也没法绕开这个hook，就挺蛋疼的

**Comment by MotooriKashin** [comment]
是的，tampermonkey注入脚本似乎和安装顺序有关，序号太大肯定慢于网页原生脚本，而且tampermonkey注入模式默认不是即时注入，更加无法保证注入时机。

**Comment by indefined** [comment]
随便写个兼容算了，issue先放着把等几天没别的问题我再关了
