### ISSUE TITLE
网页全屏下面的礼物栏

### ISSUE THREAD

**Issue by yangke9** [indefined/UserScripts#5]
我个人觉得下面的礼物栏不是很习惯，可以增加个选项么？

**Comment by indefined** [comment]
之前有这个打算，但现在脚本挺乱的，等我花点时间整理一下吧

**Comment by yangke9** [comment]
> 之前有这个打算，但现在脚本挺乱的，等我花点时间整理一下吧

好的，期待大佬

**Comment by indefined** [comment]
resloved in 2c70569d692d1d489383de19655b3a0ceeedffcb
