### ISSUE TITLE
[bilibili网页端首页增加APP首页推荐]排行榜功能开关

### ISSUE THREAD

**Issue by wk4work** [indefined/UserScripts#50]
能否在设置中增加一个排行榜功能的开关?

**Comment by indefined** [comment]
意思是不显示全站排行？倒也不是不可以，但是右边那会有一块空的，我最初就是看着太怪不打算更改布局才把排行榜加进去的

**Comment by wk4work** [comment]
> 意思是不显示全站排行？倒也不是不可以，但是右边那会有一块空的，我最初就是看着太怪不打算更改布局才把排行榜加进去的

推荐内容2x6, 或者调整下宽度?

**Comment by indefined** [comment]
> > 意思是不显示全站排行？倒也不是不可以，但是右边那会有一块空的，我最初就是看着太怪不打算更改布局才把排行榜加进去的
> 
> 推荐内容2x6, 或者调整下宽度?

B站的首页样式是自适应的，不同分辨率屏幕有不同的列数，把推荐框架拉宽到右侧就意味着要把所有分辨率的显示都测一下，并且右侧那一块和推荐块宽度并不是倍数关系，B站新版首页这些推荐块是弹性布局的，不成倍数的块会被强行平均拉宽导致间隔不一样，总之怎么放都对不齐的，并不想去折腾它……
