### ISSUE TITLE
HTML5视频截图器	0.4.15 在 https://www.agefans.net/play/20210120?playid=1_1 中不兼容

### ISSUE THREAD

**Issue by sojey** [indefined/UserScripts#51]
1. 脚本名称：

HTML5视频截图器	0.4.15

2. 脚本使用环境：

win10 19042.844 2560*1440 125%缩放

3. 问题详细描述：

加载该脚本，会让 https://www.agefans.net/play/20210120?playid=1_1 等该网站下大多数视频出现无法加载的情况。

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
试了一下，大概是匿名跨域造成的，脚本说明里写了匿名跨域只能解决一部分无法下载问题，更多情况会造成副作用，当网站不允许匿名访问时视频就会出问题，因为age之类的网站的视频来源复杂所以不同视频表现也不一样，不兼容时只能在设置里关了匿名跨域
