### ISSUE TITLE
[B站网页端添加APP首页推荐] 显示视频推荐会产生错位

### ISSUE THREAD

**Issue by datou1996** [indefined/UserScripts#52]
1. 脚本名称：
B站网页端添加APP首页推荐

2. 脚本使用环境：
Windows10 19042.844 Chrome 91.0.4442.4（正式版本）dev （64 位） Tampermonkey 4.11 1920x1080 100%缩放

3. 问题详细描述：
我的电脑b站首页默认是一行显示6个视频，如果设定脚本自动刷新页数为一页则会在最后一行中少显示两个视频，设定两页再少两个视频以此类推。

![QQ截图20210315085501](https://user-images.githubusercontent.com/14991024/111091115-e7fcd200-856c-11eb-8d8f-0a4d26d841bb.png)

![QQ截图20210315085522](https://user-images.githubusercontent.com/14991024/111091128-f2b76700-856c-11eb-92e6-c1f885ebd2e3.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
嗯，这是已知问题，并且也没什么解决方法的样子，B站这个首页的接口固定是一次10条数据并且不接受指定页面大小，新版首页是弹性布局的并且宽度根据分辨率自动适配，所以不成倍数的会错位。目前来说，只能建议把设置里的页面显示限制改成行的倍数，比如24个显示4行或者30个显示5行，超出的会被清除掉就不会错位了，或者是把保存历史调大一点，下方显示的是旧的内容应该不影响使用
