### ISSUE TITLE
[bilibili直播间工具] 直播间未开播脚本就不工作

### ISSUE THREAD

**Issue by Tinpa** [indefined/UserScripts#56]
1. 脚本名称：bilibili直播间工具

2. 脚本使用环境：macOS high Sierra 10.13.6 Chrome 89.0.4389.128（正式版本） (x86_64) Tampermonkey4.12

3. 问题详细描述：似乎当前直播间未开播脚本就不会工作 如果这是刻意设计那请问是否能手动开启“当直播间未开播使仍然启用脚本”
十分感谢！

![屏幕快照 2021-04-22 17 17 24](https://user-images.githubusercontent.com/36250538/115689524-bc9cac80-a38e-11eb-8629-e4b5e6cda35f.png)
![屏幕快照 2021-04-22 17 17 43](https://user-images.githubusercontent.com/36250538/115689535-bf979d00-a38e-11eb-8022-14d84b3f04e4.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by Tinpa** [comment]
脚本版本：0.5.34

**Comment by indefined** [comment]
除了播放器内的功能之外其它功能在未开播的时候应该也是可用的。是每个直播间都这样吗还是特定房间号？按F12查看控制台(Console)内是否有相关红色报错信息

**Comment by Tinpa** [comment]
我单独设置了一个纯净的Chrome环境测试过了，问题还是一样：**所有未开播**的直播间都**不会**激活（直播，轮播脚本就是激活的），console并没有任何红色报错

macOS high Sierra 10.13.6 Chrome 版本 89.0.4389.128（正式版本） (x86_64) Tampermonkey4.12 脚本版本：0.5.34

**Comment by indefined** [comment]
理了一下挺迷的，我这边测试了是正常的，似乎也没什么能导致未开播崩溃的地方，如果是运行崩溃的话应该有报错才对。
不会激活是指脚本没有运行（Tampermonkey的图标上没有这个脚本）还是脚本运行了但是没有作用？如果是指前一种可能的话未开播时的网址是什么样的？如果是后一种的话，你尝试编辑一下脚本删除里面大约925行的`this.elementAdjuster.init(this.settings);`然后保存看看其它功能有没有生效

**Comment by Tinpa** [comment]
准确来说是 脚本运行了但是没有作用（Tampermonkey的图标上有这个脚本），也就是后一种 删除了`this.elementAdjuster.init(this.settings);` 还是一样，未开播的直播间没作用，删除以后在能作用的页面连替换包裹图标的辣条也消失了：
![屏幕快照 2021-04-23 08 44 09](https://user-images.githubusercontent.com/36250538/115802024-ac2d1600-a410-11eb-8e2f-705527f9684e.png)
![屏幕快照 2021-04-23 08 45 46](https://user-images.githubusercontent.com/36250538/115802030-adf6d980-a410-11eb-9e8b-d1cd6b8edb5b.png)
![屏幕快照 2021-04-23 08 46 10](https://user-images.githubusercontent.com/36250538/115802034-b0593380-a410-11eb-885e-e969c1b32125.png)

**Comment by indefined** [comment]
折腾了一下似乎是有这个BUG，在全新安装没有更改过设置的情况下读取到的设置全是空的，未开播状态因为没有设置界面不会处理这些初始值所以全部功能不生效，找个开播的房间随便更改一个设置项然后再改回来试试，如果是这个问题晚些我推个更新

**Comment by Tinpa** [comment]
感谢。
