### ISSUE TITLE
[bilibili直播间工具] 礼物接口里面的二级礼物窗口无法显示

### ISSUE THREAD

**Issue by Tinpa** [indefined/UserScripts#57]
脚本名称：bilibili直播间工具 0.5.35

脚本使用环境：macOS high Sierra 10.13.6, Chrome版本 90.0.4430.85（正式版本）(x86_64), Tampermonkey4.12

问题详细描述：当在送礼接口点击任意礼物后不会弹出选择礼物数量的二级窗口。似乎在上个版本也不会显示。我回滚了几个版本发现一样的事情发生了（在那个旧版的时候是可以正常工作的），所以我猜测是b站改了点什么东西？

![屏幕快照 2021-04-25 15 29 46 (2)](https://user-images.githubusercontent.com/36250538/115984798-7e47fd00-a5db-11eb-9ef9-22fa07537437.png)

**Comment by indefined** [comment]
B站改版的原因，这个东西是上上个改版留下来的东西了，基本也就只能看看罢了，能显示基本也没法赠送，这部分模块也没什么作用代码还大部分是重构前的样子，因为也没什么印象以前的界面长什么样了所以随便修了个新界面

**Comment by Tinpa** [comment]
一般来说在当前直播间自带的礼物列表能显示的都能送，**亿元**只能从包裹里送出，除了那些以外其他的礼物都送不出去，目前除了**233**/**666**还能通过接口送，即使它已经被移出了自带的礼物列表，以前**爱心便当**也能通过接口送出去，现在是不行了
