### ISSUE TITLE
[bilibili直播间助手] 播放器相关功能失效了

### ISSUE THREAD

**Issue by Mishasama** [indefined/UserScripts#58]
1. 脚本名称：bilibili直播间助手 0.5.36

2. 脚本使用环境：Win10 Chrome90 Tampermonkey4.12

3. 问题详细描述：直播播放器的齿轮被删除了，导致一系列的功能失效了。

![image](https://user-images.githubusercontent.com/54498172/117473915-6b4b0a80-af95-11eb-978b-8a46bccebf6e.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
嗯……播放器功能失效是因为播放器逻辑又改了，和齿轮删除倒不是很大关系，我折腾一下看看到底是哪里问题吧。虽然齿轮这边确实也要处理，因为没了齿轮就没法改设置了，但是现在还没想好要自己搞一个齿轮在原来那里还是把设置放在换勋章头衔那边，不管哪边都要重新折腾一个UI挺蛋疼的

**Comment by indefined** [comment]
设置加到弹幕设置的那个按钮上去了，看着可能最近还会改的样子，先放着吧
