### ISSUE TITLE
[bilibili网页端添加APP首页推荐]刷新的快捷键

### ISSUE THREAD

**Issue by Ryan-relme** [indefined/UserScripts#59]

**Comment by indefined** [comment]
截图工具？加个刷新快捷键倒是不难，问题是似乎没这个需要，如果你开了播放器悬停快捷键并且有作用那应该用不到刷新，反正鼠标停在哪个视频就可以用，如果播放器悬停快捷键不能用那反正都需要打开工具栏加刷新快捷键意义也不大，现在已经一堆快捷键了设太多还不好记。这个脚本因为结构设计不合理原因后面扩展限制比较大，除非彻底重构一遍否则非必要功能现在不怎么想更新它

**Comment by Ryan-relme** [comment]
我是想说那个哔哩哔哩首页推荐是不是可以整个刷新快捷键的, 发错地方了, ,应该去那个仓库的

**Comment by indefined** [comment]
仓库是没错，不过这个仓库了放了好几个乱七八糟的脚本。我在反馈模版里已经提示了要说明脚本名，但是你这个反馈无论是正文还是标题都没有提及
