### ISSUE TITLE
[bilibili直播间助手]希望能增加一个选项把全屏弹幕发送框居中放置

### ISSUE THREAD

**Issue by HYY-zh** [indefined/UserScripts#60]
[bilibili直播间助手]
希望能增加一个选项把全屏弹幕发送框居中放置
网页全屏的时候是在中间，全屏之后变到左边有点怪怪的("▔□▔)/

**Comment by indefined** [comment]
你是什么浏览器以及屏幕分辨率是多大的？有你说的问题截图以及想要的位置示意吗？我这边无论网页全屏还是全屏都是在靠右边的，脚本里直接把弹幕发送框放在播放器里的功能逻辑是把它添加到右侧几个按钮后面，因为B站直播的这几个按钮是逆向排序的所以弹幕发送框应该会在右侧几个按钮的左边，相对于屏幕的位置只能说和屏幕的分辨率有关，如果不是兼容或者逻辑错误的话应该也不好改，强制居中有可能会覆盖遮挡到一些按钮，因为每个人看直播的分辨率可能不一样

**Comment by HYY-zh** [comment]
是谷歌浏览器，分辨率是1080P，我这边全屏是靠左的
![image](https://user-images.githubusercontent.com/61227595/119365434-81b9cb80-bce2-11eb-9729-ddfdadf4cfb9.png)
网页全屏的时候是居中的
![image](https://user-images.githubusercontent.com/61227595/119365584-a57d1180-bce2-11eb-9965-479204b1e7ce.png)
有时候还会卡出两个发送框
![image](https://user-images.githubusercontent.com/61227595/119365705-cb0a1b00-bce2-11eb-9c63-42317743620c.png)
不过都在刷新网页后变成靠左
可能是我这边跟其他脚本有冲突吧

**Comment by HYY-zh** [comment]
是谷歌浏览器，分辨率是1080P，我这边全屏是靠左的
刚刚试了一下是跟另一个脚本Bilibili Evolved的直播全屏弹幕栏有冲突导致靠左了
![image](https://user-images.githubusercontent.com/61227595/119366954-1113ae80-bce4-11eb-8b26-3a80978ce332.png)
如果改的麻烦的话就算了吧，只是个人感觉不居中的话会有点不对称_(:3」∠)_

**Comment by indefined** [comment]
试了一下是冲突了，关掉其中一个设置应该就好了，因为是重复的功能应该没必要两个都开，我看了一下Bilibili Evolved里面的那个全屏发送栏是居中的，如果只想要居中的那个的话，在播放器里的那个弹幕按钮上把这个脚本的全屏弹幕栏关掉应该Bilibili Evolved里的就不会出问题了，如果想要这个脚本里的全屏发送栏的话，关掉Bilibili Evolved设置里的全屏发送栏那这边的应该就不会变到左边了（理应是在右边的）

**Comment by HYY-zh** [comment]
好的ヽ(￣▽￣)و
