### ISSUE TITLE
[App首页推荐] 视频右上角没有X按钮

### ISSUE THREAD

**Issue by cikichen** [indefined/UserScripts#61]
1. 脚本名称：
bilibili网页端添加APP首页推荐

2. 脚本使用环境：
chrome 版本 91.0.4472.77（正式版本） (arm64) 100%

3. 问题详细描述：
![image](https://user-images.githubusercontent.com/1478821/120928500-7a99b100-c717-11eb-90dc-82ae0977639e.png)
鼠标悬浮只会出现进度条，右上角没有不喜欢按钮出现

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
需要在设置里授权之后才会出现X按钮和不喜欢选项的，授权过的吗？
