### ISSUE TITLE
[bilibili CC字幕] 长视频加载本地字幕，后半段不生效

### ISSUE THREAD

**Issue by a776058959** [indefined/UserScripts#62]
1. 脚本名称：

Bilibili CC字幕工具 0.5.21
2. 脚本使用环境：

Win10    Microsoft Edge 版本 93.0.916.1     暴力猴v2.13.0
3. 问题详细描述：

长视频，大概是超过一个小时的视频，加载本地字幕，到了后边就没效果了，重新加载字幕或者刷新网页再重新加载字幕也不行，字幕是油管下载的自动生成的SRT格式，而且字幕文件里边不缺东西

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
能提供一下视频和字幕吗？油管和B站的链接就可以了我试一下
