### ISSUE TITLE
能否开发个获取b站手机客户端cc字幕的脚本？比如抓取b站东南亚版app的外挂字幕。

### ISSUE THREAD

**Issue by YFTX2015** [indefined/UserScripts#63]
<!--如果你的请求基于一个已存在问题，请描述该问题.>

<!--描述你想要的功能、解决方案>

**Comment by indefined** [comment]
区域限制的番剧字幕有一些是需要代理服务器的，如果没有其它工具的话视频本来就没法播放的所以我这边并没有做代理的打算。https://github.com/ipcjs/bilibili-helper 解除区域限制的脚本里已经包含有字幕区域的解锁，如果视频能播放那字幕也应该正常能获取，如果不能的话，先试试把字幕脚本删除然后重新安装一遍（字幕脚本需要运行在区域解锁脚本后面）

**Comment by YFTX2015** [comment]
pc网页端抓字幕自然是没问题，f12，脚本都比较容易操作。而且不管是网页播放器还是app内部播放器，播放国外视频都没问题，字幕都能正常加载，区域问题梯子就能解决。关键是在app里面怎么抓字幕？我曾经用fiddler, mitmproxy, httpcannary试过，抓取bilibili global国外视频源，字幕都失败。这些工具都是一启动，就会自动建立一个代理，然而这就会与梯子的代理冲突，从而导致获取数据失败。而且还有证书通不过验证获取不了https链接等一系列问题。

**Comment by indefined** [comment]
你的意思是想知道怎么用工具自己抓取手机APP需要代理的内容？这个脚本我也做不到啊。调试抓取工具正常都有前置代理选项的，像fiddler里面的option→gateway，开梯子并暴露出代理端口地址，然后在抓取工具里把前置代理设置为梯子的代理地址，设置暴露抓取工具的代理端口地址，最后把手机的代理设置为抓取工具，数据流就是 手机→抓取工具→梯子→服务器。证书问题现代手机无解，你只能找个安卓6.0或者更老的手机，安装抓取工具的自定义证书并添加为信任，新手机因为系统安全限制除非你root了否则无法信任非机构证书，我现在自己也抓不了

**Comment by indefined** [comment]
或者是电脑上安装个安卓模拟器可能比较容易解决把，虽然我没试过也不知道怎么操作

**Comment by YFTX2015** [comment]
我的荣耀v30目前好像root不了。安卓模拟器也试过，由于bilibili global是个相当奇葩的东西，不仅要代理，而且手机里面不能有中国手机卡，否则打开都是一片空白。由于是从google play获取的应用，即使单独导出apk安装在模拟器里面也会出问题，基本打开就会闪退。资源搬运组里面有个叫nc-raws和一个叫dd动画的，他们就是专门搬运b站国际版番剧的组，然后在各大bt站和tg群里面发布。更新也相当快，基本上b站源一出，最多几分钟就能抓下来并发布出去。我到nc-raws tg群里面去问过，他们说用的就是脚本，视频跟字幕都能抓，然而却不愿透露，真不知是怎么办到的。

**Comment by indefined** [comment]
他们说的脚本和你理解的脚本可能不是一个东西，任何自动化程序可能都会被叫做脚本，但我这个脚本只是网页端的用户扩展脚本罢了。本质上做一个专门抓取东南亚APP字幕的程序或者网页脚本也不是不可能，不过前面我也说了这边并没有做代理服务器的打算，只要一个东南亚字幕的功能太小众了不值得我去重复折腾一个代理服务器来做这种事情。如果你只是想要自己在电脑上看某个东南亚特供的番剧和字幕的话，我上面说的https://github.com/ipcjs/bilibili-helper 这个解锁区域脚本似乎是可以做到的，虽然你可能需要去找一下别人提供的代理服务器以及研究一下怎么找番，它不仅可以解锁网页端东南亚的番剧也可以顺便把字幕也解决了。正常情况下的话，如果你已经可以在网页端看东南亚的番剧了，那用这个脚本也可以顺便把字幕下载下来并不需要更新。但是如果你要批量下载东南亚字幕，那应该没有什么公开的脚本程序什么的有这个功能，我也没有做这个的计划

**Comment by YFTX2015** [comment]
主要是我想要的中字只有app才有。网页端就是个摆设，不仅番剧数量有限，而且只有泰文字幕，清晰度也没法调。不然我也不会那么纠结在app里抓字幕了。既然你这边只做网页端的脚本，那我也不好再麻烦你了。不过你提到的bilibili-helper,我倒可以问问那边的开发者，看有没有意向做app方面的抓包工具。
