### ISSUE TITLE
希望不显示排行榜后推荐页面可以拓宽，一大块空白看着难受

### ISSUE THREAD

**Issue by oxfrog666** [indefined/UserScripts#65]
![ff70a361a137e5a7b8f850a9c20a357](https://user-images.githubusercontent.com/81603854/124297144-56ea4f00-db8d-11eb-8932-d82fe227cb5b.png)

**Comment by indefined** [comment]
这个问题其实我已经回答过了，首页内容的布局本来就没有为全宽考虑，这个脚本也只是用了首页的原布局，强制加宽会导致对不齐，也就是从一个地方难受变成另一个地方难受罢了，不过既然你们更喜欢加宽那我就加宽吧

**Comment by oxfrog666** [comment]
提个建议哈，可以将加宽设置为可选项，让用户自由选择。
