### ISSUE TITLE
[bilibili直播间助手] 断网重新加载问题

### ISSUE THREAD

**Issue by Mishasama** [indefined/UserScripts#69]
1. 脚本名称：
bilibili直播间助手 0.5.39

2. 脚本使用环境：
Chrome			91.0.4472.124
Tampermonkey	v4.13

3. 问题详细描述：
现在有个小问题，网络不好断线的时候，重新连上时会触发播放器整个重新加载（重绘？）还是咋的，相关的模块就没了。
由于原装的全屏弹幕输入被改动过了，所以在全屏模式下也不能发弹幕了。
如果要应对这种状况而不需要刷新页面的话，也许需要做个状态检测，每次触发的时候再生成一遍相关的模块？

![image](https://user-images.githubusercontent.com/54498172/125322743-0fc44100-e379-11eb-9180-8c8822a0faa9.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
我这边没办法复现这种情况，刻意断网也没办法让它重新加载。实际是播放器重新加载会导致功能异常是一开始就预知到的，包括之前还有FLASH播放器时切换播放器或者打开房间时未开播但是过后开播的情况脚本大部分播放器内的模块都无法正常工作，这并不是重新生成的问题，这个脚本播放器内的功能基本不会生成页面元素，它只是搬运和改变显示已经存在的页面内容，而重新加载那些“已经存在的内容”可能就变成不存在了。目前来说我并没有找到检测播放器重新加载的方法，假使可以获取，实际在不刷新下重新初始化也会很复杂，因为每个模块哪些变了哪些要用旧的哪些要用新的判断起来都很麻烦，会遇到的情况也比较少，目前只能建议还是手动刷新

**Comment by Mishasama** [comment]
找到我这边的必然重现步骤了

0. 首先确保以下浏览器环境：已经打开的标签页在30个以上，Chrome 91以上
1. 打开正在直播的直播间
2. 确保脚本正常运行，不要进入任何的全屏模式，保持默认的界面
3. 在同一浏览器窗口打开新的分页
4. 在确保后台的直播间分页正常播放音频
5. 继续在新的分页进行正常浏览活动
6. （可选）再打开一个新的分页，并且该分页也是个正在直播的直播间并正常播放音频
7. 确保两个小时以上没有激活（查看）过要测试的分页
8. （可选）断网重连，确保要测试的后台分页的音频能重新连上并继续播放
9. 查看要测试的分页，发现播放器相关元素没了
10. 但随便进入任何一个全屏模式能看到咱们新增的时间同步按钮，不过移动了的官方全屏发弹幕的模块就没了

疑似是因为浏览器的某个节约后台分页资源而【卸载】部分页面内容的功能而导致此问题的，确实不容易解决。
我问了几个人貌似都没想到要怎么弄，如果没兴趣研究对策的话那就关掉这个issue吧。

**Comment by indefined** [comment]
……这个步骤我基本可以认为它是无法复现的了，且不说里面有几个是必要的，单保持两个小时就完全无法测试了，因为需要的不仅是它重载的结果，还需要捕捉到它重载的过程我才能调试。姑且问一句，重载之后全屏礼物栏存在吗？如果不存在那全屏发送弹幕不存在也很正常，因为它被移动到礼物栏内了，如果礼物栏存在，那说明是原先的弹幕发送框被销毁了，虽然很神经病并且我也没办法测试，不过根据你的回答我可能会尝试每次进全屏都重新获取这两个东西的其中一个，这会影响网页性能但或许可以解决弹幕发送框的问题。至于设置界面消失我就不想去管它了，改起来问题太多

**Comment by Mishasama** [comment]
最新HEVC版：
普通状态礼物没位移、播放器增加的同步按钮消失
网页全屏礼物栏不在、全屏弹幕输入栏没有，但侧栏模式在
全屏模式同步按钮在，礼物栏、全屏弹幕输入栏没有

**Comment by Mishasama** [comment]
至于两个小时的测试问题，我这边再次进行模拟测试，发现并不一定是重载才会这样，也发生在后台打开分页后一直没激活该后台分页，长时间闲置后再激活也会出现这个情况。

我能看到播放器一瞬间出现了长时间闲置而弹出的倒计时提问然后消失，播放器开始载入直播串流。但是页面元素看上去是完全载入完毕的。（至少渲染的速度非常快，像是预加载/预渲染好的样子，可能只是没进行显示？）
但激活分页之前并没有听到直播的声音，推测并没有实际在加载串流，这应该是浏览器的一些优化策略导致的。

**Comment by indefined** [comment]
那可能不是浏览器的优化而是B站的防挂机功能，但是我并不是很确定它到底是怎么工作的。从你的状态描述我也没理清重载之后到底是什么状态——原则上来说，播放器重载会发生问题应该是控制栏和发送弹幕栏被重新生成了，因为这个脚本的礼物栏、时间同步、全屏发弹幕功能都是把东西移动到控制栏里面，但是这三个功能用的是同一个控制栏，如果只有发送弹幕不能用那就是弹幕发送框被重新生成了，这个应该比较好解决，除此之外不应该有些能用另一些却不能用，更不应该出现普通状态没有同步按钮但是全屏却有，要么它们一起失效要么一起有效那么我还可以尝试一下获取控制栏，一部分有效一部分无效就没法解释了，如果非要解释，那只能是播放器生成了两个控制栏，在部分情况下用其中一个另一种情况下却用另一个控制栏，如果真是这样那情况就复杂到以目前的结果没法解决了。
不过总的来说，如果它真的是防挂机导致的，你或许可以试一试用别的脚本里的屏蔽挂机检测，比如这个 [bilibili直播净化
](https://greasyfork.org/zh-CN/scripts/21416-bilibili%E7%9B%B4%E6%92%AD%E5%87%80%E5%8C%96) 如果没有用的话那只能等我用空试试能不能重现，现在我应该没空去调试它

**Comment by Mishasama** [comment]
![image](https://user-images.githubusercontent.com/54498172/126345867-ee1e20a9-84d6-4ca7-9183-6af61056aea1.png)
在用……😂

另外我刚又掉线了，发现了个更有趣的情况。

播放器重新连上串流之后，时间同步消失了。
在播放器显示控件的时候双击播放器进入网页全屏状态，只要鼠标停留的位置合适，控件没有消失掉的话时间同步按钮会出现，但是礼物和全屏弹幕输入还是没有。不过一旦鼠标离开导致控件消失，然后再移动鼠标让它再显示的话时间同步的按钮也没了。
不过还是能通过退出网页全屏，然后再次通过上述方式进入全屏来看到同步按钮，但是依旧会因为控件的消失而再次无法显示。

上面说的网页全屏和显示器全屏的效果一致，都是在控件栏不消失的时候进去则能看到按钮。


另外根据你的说明，我想起了B站的播放器加载逻辑就是两个播放器的……
当一个播放器或串流崩溃或者无法加载时就会载入另一个播放器，这是通过
![image](https://user-images.githubusercontent.com/54498172/126347182-dfbcc6c2-9ceb-405c-baa1-be6193e71745.png)
这个自带的功能看出来的。当出现两个播放器的时候状态数据会在两个播放器之间来回跳动，而且很偶发性的还能出现音画不同步的情况。

**Comment by indefined** [comment]
那应该是两个播放器的问题了。等我想想能不能给脚本换个结构吧，目前的结构没法解决多个播放器问题

**Comment by indefined** [comment]
现在的播放器内三个模块工作逻辑有较大差异，时间同步已经是完全独立的逻辑了应该不会受重载影响，礼物栏和弹幕发送栏现在每次全屏都会重新查找获取，但是我没有办法重现问题所以也没法测试，如果你那边比较容易触发的话可以测试一下。设置按钮由于是添加到原有控制栏的菜单上的所以没法随时获取，但是我做了一个比较神经病的判断逻辑来重载它，同样因为没法测试也不知道效果。如果你遇到重载的问题的话，可以顺便也看看设置内容在不在
