### ISSUE TITLE
bilibili APP首页推荐 添加数量

### ISSUE THREAD

**Issue by ZDYYY** [indefined/UserScripts#7]
不知道可不可以在后续的版本中增加猜你喜欢的单页显示个数，不然要不断的按刷新，也可以充分发挥电脑屏幕大的优点。

**Comment by indefined** [comment]
其实显示更多数量已经做了，不过对于UI要怎么展示没考虑好所以没推上去，不限制高度的话会导致页面没对齐看上去不和谐，增加滚动条也不好看，目前做了滚动框可选择保存以前猜你喜欢历史，不过每次打开还是只会自动刷新一页，我考虑一下把增加高度设置和刷新页数的逻辑吧，如果暂时不好做就先把目前的滚动框推上去

**Comment by ZDYYY** [comment]
啊，作者居然回我信息了，太感谢你的贡献了，祝你一切顺利安心


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: indefined <notifications@github.com>
发送时间: 2019年5月31日 20:52
收件人: indefined/UserScripts <UserScripts@noreply.github.com>
抄送: ZDYYY <814429616@qq.com>, Author <author@noreply.github.com>
主题: 回复：[indefined/UserScripts] 添加数量 (#7)




其实显示更多数量已经做了，不过对于UI要怎么展示没考虑好所以没推上去，不限制高度的话会导致页面没对齐看上去不和谐，增加滚动条也不好看，目前做了滚动框可选择保存以前猜你喜欢历史，不过每次打开还是只会自动刷新一页，我考虑一下把增加高度设置和刷新页数的逻辑吧，如果暂时不好做就先把目前的滚动框推上去

**Comment by indefined** [comment]
已推送更新，改动较大可能会有BUG，如有问题再反馈

**Comment by dawn-lc** [comment]
保存推荐数量 无效，超过设置的数值后没有删除多余的推荐内容

**Comment by indefined** [comment]
> 保存推荐数量 无效，超过设置的数值后没有删除多余的推荐内容

嗯……用浏览器版本和脚本管理器是什么？更改保存推荐数量设置按F12控制台里有无报错？现在做的逻辑是在关闭页面的时候才删除多余内容保存的，下次打开的时候显示的应该是保存的数量加上自动刷新的数量，页面内容是不会自动删除多余内容的，没有实时保存是因为考虑到一次打开可能会多次加载更多内容和更改设置数值，监听页面关闭的浏览器兼容性我也不是很清楚，如果存在兼容问题的话我就改回实时保存吧

**Comment by dawn-lc** [comment]
> > 保存推荐数量 无效，超过设置的数值后没有删除多余的推荐内容
> 
> 嗯……用浏览器版本和脚本管理器是什么？更改保存推荐数量设置按F12控制台里有无报错？现在做的逻辑是在关闭页面的时候才删除多余内容保存的，下次打开的时候显示的应该是保存的数量加上自动刷新的数量，页面内容是不会自动删除多余内容的，没有实时保存是因为考虑到一次打开可能会多次加载更多内容和更改设置数值，监听页面关闭的浏览器兼容性我也不是很清楚，如果存在兼容问题的话我就改回实时保存吧

Google Chrome
版本 74.0.3729.169（正式版本） （64 位）

Tampermonkey v4.8.41

**Comment by dawn-lc** [comment]
> > 保存推荐数量 无效，超过设置的数值后没有删除多余的推荐内容
> 
> 嗯……用浏览器版本和脚本管理器是什么？更改保存推荐数量设置按F12控制台里有无报错？现在做的逻辑是在关闭页面的时候才删除多余内容保存的，下次打开的时候显示的应该是保存的数量加上自动刷新的数量，页面内容是不会自动删除多余内容的，没有实时保存是因为考虑到一次打开可能会多次加载更多内容和更改设置数值，监听页面关闭的浏览器兼容性我也不是很清楚，如果存在兼容问题的话我就改回实时保存吧



> > 保存推荐数量 无效，超过设置的数值后没有删除多余的推荐内容
> 
> 嗯……用浏览器版本和脚本管理器是什么？更改保存推荐数量设置按F12控制台里有无报错？现在做的逻辑是在关闭页面的时候才删除多余内容保存的，下次打开的时候显示的应该是保存的数量加上自动刷新的数量，页面内容是不会自动删除多余内容的，没有实时保存是因为考虑到一次打开可能会多次加载更多内容和更改设置数值，监听页面关闭的浏览器兼容性我也不是很清楚，如果存在兼容问题的话我就改回实时保存吧

开发者控制台没有有关删除的报错，建议加入推荐数量上限

**Comment by indefined** [comment]
这就很神奇了，我用的同样的浏览器和脚本管理器没有问题啊，如果是指页面内容数量限制的话倒是可以增加一个设置，保存数量是关闭页面后下次打开才生效的确定也有没有删除吗？有问题我就改回去了

**Comment by indefined** [comment]
> 开发者控制台没有有关删除的报错，建议加入推荐数量上限

确认一下页面关闭后下次打开是否没有根据设置的推荐删除多余的？如果页面关闭后保存的数量没有错误，只是需要页面内的显示限制的话，那我就只增加页面内容限制的设置，保存数量那里就不改回实时保存了，这个方法应该兼容性挺好的，改回实时刷新有一定的副作用；如果确认页面关闭后重新打开也没有删除多余的旧推荐的话那我就把保存推荐数量改回实时保存

**Comment by indefined** [comment]
推荐上限设置已经增加，保存数量没有调试出问题因此没有更改，如果明确保存数量限制没有生效务必反馈

**Comment by indefined** [comment]
没有新情况本issue关闭，如有相关BUG可继续回复将重新打开讨论
