### ISSUE TITLE
[bilibili直播间工具] 无法硬币购买直播间的勋章

### ISSUE THREAD

**Issue by shinji-ikari** [indefined/UserScripts#70]
1. 脚本名称：bilibili直播间工具 0.5.39.1

2. 脚本使用环境：chrome 最新版 + tampermonkey最新版

3. 问题详细描述：没办法硬币购买直播间的勋章 , 点击购买最后显示 `购买勋章失败 code -1 兑换失败, 请升级到最新版本`

<details>
<summary>错误报告</summary>
<pre>
<code>

没有.按了一下F12看,没发现有任何相关的代码.
</code>
</pre>
</details>

**Comment by shinji-ikari** [comment]
对了,现在弹幕框左边不是会显示当前佩戴的勋章么? 点击一下可以显示3个勋章的,并且可以确认勋章的直播间有没有在直播.
脚本能不能增加这个显示勋章的数量?  主要是这个可以确认直播间有没有在播. 当然,这个只是顺嘴问一下能不能的. 感觉有可能会很麻烦或者实现不了,所以只是问问,如果大大有考虑再看看呗.没也不影响_(:з」∠)_

**Comment by indefined** [comment]
说明B站已经禁用这个接口了，这个购买功能是很老版本的APP里的接口了，B站最近骚操作这么多旧版被关掉也是早晚的事，我看了一下新版APP里早就没有这个购买功能了，所以我也没办法解决，下次更新应该会删掉这个功能。原生显示切换勋章那里，很麻烦。因为那个悬浮窗是动态生成并且关闭就会销毁的，捕捉到窗口再去添加东西很麻烦，自己创建一个很原生切换长一样的我个人是觉得没必要，因为那个样式信息密度小占用空间大却显示不了多少东西。开播状态是可以添加的，我考虑一下怎么塞到现在的勋章列表上吧

**Comment by Andy8r0X** [comment]
好可惜，未来只能用钱买了! 谢谢作者的功能让我换到数个勋章

**Comment by shinji-ikari** [comment]
被里币关了就没辙儿了. 谢谢大大的脚本了
