### ISSUE TITLE
[bilibili直播间助手] 活动直播间模板时间同步不出现

### ISSUE THREAD

**Issue by Mishasama** [indefined/UserScripts#72]
1. 脚本名称：
bilibili直播间助手

2. 脚本使用环境：
Win10 Chrome 92.0.4515.107 Tampermonkey 4.13

3. 问题详细描述：
无论是普通、窗口全屏、还是真全屏都没有，看来需要对特殊样式处理一下了。

![image](https://user-images.githubusercontent.com/54498172/128717227-b357a7fe-385a-4198-aaf8-58ee453ae060.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
生草非跨域可以直接读顶层的全局变量，省事了能用的话就先这样吧
