### ISSUE TITLE
[bilibili网页端添加APP首页推荐] 新版首页适配问题

### ISSUE THREAD

**Issue by indefined** [indefined/UserScripts#76]
目前B站开始了新版的首页灰度测试，一部分人主页会变为新样式，[(关联](https://greasyfork.org/zh-CN/scripts/368446-bilibili%E7%BD%91%E9%A1%B5%E7%AB%AF%E6%B7%BB%E5%8A%A0app%E9%A6%96%E9%A1%B5%E6%8E%A8%E8%8D%90/discussions/96795)
![image.png](https://i.loli.net/2021/08/24/JNrpnVbKu9STUzB.png)

目前此脚本未适配新版主页，是否适配或者停止更新尚在考虑中，总之至少近期不会很快跟进，如果真的有需要使用此脚本请点击新版右下角的返回旧版。
如有意向自行实现新版适配在MIT许可下请自由修改发布，后续我可以在readme中加入新版引导，不过因为此脚本结构极其混乱以及此工程下还有其它乱七八糟的脚本，所以不建议直接fork修改，建议有能力的最好重构

**Comment by hukewei2001** [comment]
app授权不成功

**Comment by GoTop** [comment]
这个脚本没适配新页面，我在电脑上看b站的时间少了很多

**Comment by mlch911** [comment]
希望适配

**Comment by magicdawn** [comment]
fork 了一个简易的自用, 需要自取
https://github.com/magicdawn/bilibili-app-recommend

**Comment by D3DSKELL** [comment]
> fork 了一个简易的自用， 需要自取 https://github.com/magicdawn/bilibili-app-recommend

非常感谢！

**Comment by magicdawn** [comment]
B 站桌面端已上线, 支持 MacOS / Windows, 首页包含推荐模块

![image](https://user-images.githubusercontent.com/4067115/169683392-2ed72442-5d4a-42cc-aa6c-6398b4b0517b.png)
