### ISSUE TITLE
[bilibili首页推荐]请求增加高清封面的功能

### ISSUE THREAD

**Issue by sixiansheng** [indefined/UserScripts#77]
![image](https://user-images.githubusercontent.com/35787924/132098460-b1f18b54-b70c-434d-ae12-51d4a1ccfe5d.png)

**Comment by indefined** [comment]
增加高清封面是指把略缩图的分辨率提高还是提供一个原始高分辨率的封面下载打开功能？说实话两个都不难，封面的分辨率实际是可调的我只是复制了一下早期主页的那个封面分辨率，对于高分屏的人来说可能是模糊了，至于原始封面下载……不知道放哪。主要问题是现在B站的主页又要更新了，所以单独更新个封面的意义不大，因为搞不准十天半个月因为新版主页更新后这个脚本就完全失效了，所以如果要做的话大概如果下次新版兼容更新的话会一起顺带做，但是具体什么时候做现在没计划

**Comment by sixiansheng** [comment]
> 增加高清封面是指把略缩图的分辨率提高还是提供一个原始高分辨率的封面下载打开功能？说实话两个都不难，封面的分辨率实际是可调的我只是复制了一下早期主页的那个封面分辨率，对于高分屏的人来说可能是模糊了，至于原始封面下载......不知道放哪。主要问题是现在B站的主页又要更新了，所以单独更新个封面的意义不大，因为搞不准十天半个月因为新版主页更新后这个脚本就完全失效了，所以如果要做的话大概如果下次新版兼容更新的话会一起顺带做，但是具体什么时候做现在没计划

嗯嗯，现在B站更新了，要是现在做说不定过阵子就失效了，再等等吧，主要是我把其他的内容屏蔽了，然后网页放大，所以浏览的时候封面很模糊，我指的是浏览的时候看到的封面。
