### ISSUE TITLE
[bilibili直播间助手] 解析返回错误查询勋章失败

### ISSUE THREAD

**Issue by Mishasama** [indefined/UserScripts#79]
1. 脚本名称：bilibili直播间助手

2. 脚本使用环境：Win10 Chrome94 Tampermonkey4.13

3. 问题详细描述：又更新了……

![image](https://user-images.githubusercontent.com/54498172/135292281-897abfe0-f862-4dba-a324-49d1afbbbc08.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
B站好闲着蛋疼，没事改有的没的接口参数干嘛……

**Comment by Mishasama** [comment]
没弄好，获取勋章对应的直播间地址失败
![image](https://user-images.githubusercontent.com/54498172/135348374-f10d639e-fef0-4dad-a560-3716d68f8d73.png)
这些地方的链接原本指向勋章对应的直播间现在都变成这个了
![image](https://user-images.githubusercontent.com/54498172/135348481-2b1971b5-b326-43e7-9323-348e1ab7dfaa.png)
