### ISSUE TITLE
哔哩哔哩首页猜你喜欢网址匹配问题

### ISSUE THREAD

**Issue by MyFaith** [indefined/UserScripts#8]
```
// @match        *://www.bilibili.com/*
```

建议在域名后增加一个 `*`，在某些特殊情况下，首页的网址是https://www.bilibili.com/index.html ，所以脚本就没启用

**Comment by indefined** [comment]
感谢反馈，不过在所有页面下执行脚本不太好，原则上首页应该也不会有很多乱七八糟的地址，目前先把这个地址包含进去，如果确实有很多意料之外的地址再使用通配吧
