### ISSUE TITLE
[bilibili直播间工具] bilibili更新了！解析返回错误查询勋章失败 code:520002 pageSize最多10个～

### ISSUE THREAD

**Issue by Janet-Baker** [indefined/UserScripts#80]
1. 脚本名称：bilibili直播间工具

2. 脚本使用环境：

3. 问题详细描述：

解析返回错误查询勋章失败 code:520002
pageSize最多10个～

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
Duplicate of #79 新版应该已经修复了
