### ISSUE TITLE
[bilibili直播间助手] 进入直播间报错

### ISSUE THREAD

**Issue by DIXX-qqfr** [indefined/UserScripts#81]
1. 脚本名称：

2. 脚本使用环境：

3. 问题详细描述：

进入直播间后报错：“无法获取勋章列表。错误码：520002 pagesize最多10个”

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
Duplicate of #79 应该已经修复的

**Comment by Mishasama** [comment]
已修复，目前未见异常。

**Comment by DIXX-qqfr** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
