### ISSUE TITLE
[bilibili直播间工具] 接口禁用

### ISSUE THREAD

**Issue by DIXX-qqfr** [indefined/UserScripts#82]
1. 脚本名称：[bilibili直播间工具] 

2. 脚本使用环境：Win10 Chrome80 Tampermonkey4.13

3. 问题详细描述：

B站20硬币换粉丝牌的接口是禁用了吗？我试图修改老版本，但只有一个按钮样子，使用会提示“兑换失效 code-1，请升级到最新版本”，我之后又用最新版本，尝试使用该功能，同样只有一个样子，实际使用不了

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
#70 B站禁用了接口，已经无法使用了
