### ISSUE TITLE
[bilibili直播间助手] 直播中状态没刷新

### ISSUE THREAD

**Issue by Mishasama** [indefined/UserScripts#83]
1. 脚本名称：bilibili直播间助手

2. 脚本使用环境：Win10 Chrome94 Tampermonkey4.13

3. 问题详细描述：

脚本完成加载后，“直播中”这个状态就固定了，无论开播或者下播，这个列表也不会重新读取目前的状态。
没记错的话在这次改API前只要开关一下这个列表是能刷新状态的，但这次之后就只能刷新网页来获取当前的状态了。

![image](https://user-images.githubusercontent.com/54498172/135702712-80458bc6-ef48-4118-add0-fb89a0adc120.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
嗯看了下是会有这个问题。这次改API我原本是打算整个换成APP的接口去掉之前的逻辑的，但是测试发现最终还是要用之前的办法。B站的接口做得神经病乱七八糟的，一个接口没办法获取完勋章列表和直播状态，我本来以为APP的接口可以直接用结果也一样，然后因为这次接口更新不能一次获取完所有勋章要分页获取所以为了防止每一页重复获取直播状态给直播状态做了缓存，结果导致状态不更新了。本来我是还考虑过另一个获取方案，但似乎怎么搞都会缺东西的样子，还是修一修继续用以前的方案吧
