### ISSUE TITLE
[bilibili直播间助手] 隐藏付费礼物栏

### ISSUE THREAD

**Issue by Mishasama** [indefined/UserScripts#84]
不知道大佬有没有空弄一个像道具包裹旁边那样的按钮，把所有的收费道具功能全折叠了……
最近在切换全屏和退出的时候双击偶尔会发生鼠标位置和礼物位置重叠了，然后在播放器尺寸改变时还会移动到礼物的发送按钮上……导致莫名其妙的就一个大楼出去了………破站也是够恶心人的😂

**Comment by indefined** [comment]
没有做的计划。说实话我已经很久不看直播了，现有的功能也只会在不是特别麻烦的情况下保持维护，加新功能实在无力应对了，B站的网页要优化的地方太多，我改不过来的，特别是我也不擅长前端所以这种东西就更没折腾的欲望
