### ISSUE TITLE
[HV 物品装备汉化]能汉化一下拍卖网站吗？

### ISSUE THREAD

**Issue by yinzhefuyun** [indefined/UserScripts#90]
``能汉化一下拍卖网站吗？https://reasoningtheory.net
不知道怎么PR谁便改了下脚本不知道逻辑有没有问题

`===================================================================`
`--- 当前版本
+++ 新版本
@@ -15,9 +15,8 @@
 // @exclude      *://*hentaiverse.org/*equip/*
 // @exclude      *://*hentaiverse.org/*pages/showequip.php?*
 // @include      *://forums.e-hentai.org/*showtopic=*
 // @include      *://hvmarket.xyz/*
+// @include      *://reasoningtheory.net/*
 // @version      2021.09.22
 // ==/UserScript==
 
 if (document.location.href.match(/ss=iw/)&&!document.getElementById('item_pane'))return
@@ -49,9 +48,8 @@
         'Bazaar&ss=lt', //武器彩票11
         'Bazaar&ss=la', //防具彩票12
         'equip', //装备属性页13
         'hvmarket.xyz', //hvmarket14
+        'reasoningtheory.net', //reasoningtheory15
     ];
     var location;
     for(location = 0; location < lklist.length; location++){
         // 匹配当前网址位置，lklist里面的网址顺序和下面case对应，更改顺序需要同时更改case
@@ -201,13 +199,8 @@
             translateItems('.main_content>h1'); //购买页面标头
             translateItems('h2.exch'); //购买页面的购买描述
             break;
 
+        case 15: //reasoningtheory
+            translateEquips('td>a');//装备名
+            translateItems('td'); //物品列表
+            break;
+
         default: //没有匹配命中需要翻译的网页
             break;
     }`

**Comment by indefined** [comment]
自己用的话应该问题不大，装备名那样最好也改成td不然会因为物品翻译重复替换导致无法切换回原文。PR就不必了等我下次更新的话自己加上去吧

**Comment by yinzhefuyun** [comment]
> 自己用的话应该问题不大，装备和物品的汉化顺序最好调一下把装备名那行也改成td不然会因为物品翻译重复替换导致无法切换回原文。PR就不必了等我下次更新的话自己加上去吧

切换回原文好像没问题，问题最大是这个网站他1分钟就会刷新一次报价，所以它页面刷新后要再次翻译一次

**Comment by indefined** [comment]
> 切换回原文好像没问题，问题最大是这个网站他1分钟就会刷新一次报价，所以它页面刷新后要再次翻译一次

看了一下网站的代码是如果勾选自动刷新会每5分钟更新一次拍卖记录，要做也不是不可以，但是说实话挺蛋疼的，这页面放着它自动刷新加自动翻译的话如果拍品多估计按照这脚本的垃圾效率放久会卡死，我也没这么用过自动刷新基本都是打开看一下就关了，以前也是觉得没什么必要所以懒得加。具体方案我再考虑吧，不考虑它刷新的话没什么问题你先就用着吧
