### ISSUE TITLE
[bilibili直播间工具] 解析返回错误查询勋章失败

### ISSUE THREAD

**Issue by Mishasama** [indefined/UserScripts#91]
1. 脚本名称：
bilibili直播间工具 0.5.46.4

2. 脚本使用环境：
Win10 Chrome95 Tampermonkey4.13

3. 问题详细描述：
我的勋章
解析返回错误查询勋章失败 code:510001
用户不存在～

新年快乐！接口又更新了？这就是破站的新年礼物吗？！

![image](https://user-images.githubusercontent.com/54498172/147852775-a389809c-2314-4f13-9598-9dee967965eb.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
不应该。我这边没有遇到问题，不过大概能猜到问题是什么。现在用的勋章的那个接口里面有一个`target_id=`的参数，之前测试的时候似乎是必要参数不能少，指的应该是当前直播的房间。但我测试的时候这个参数是随便写无所谓的获得的数据没有区别，所以我写死了`target_id=1`，如果真的是这个东西的原因错误那可能是特定房间限定才会出现问题的，你那边可以测试一下是不是只有某个房间出错，另外我试了一下现在这个东西删掉似乎也不报错，所以你也可以测一下删掉代码里的`&target_id=1`。
另外虽然可能性不大但也有可能是因为账户cookie出现问题，之前也出现过特定API用户登陆状态无效的情况，实在没办法的话也可以试一下退出帐号重新登录

**Comment by DIXX-qqfr** [comment]
我也出现了这个问题，不是在特定的直播间，所有直播间都是如此，另外，我重登了一遍账户，也没用。

**Comment by indefined** [comment]
挺迷的，我这边没法复现问题
直接复制这两个网址到浏览器地址栏打开最前面是否有code 510001？（不要直接点开会报错
https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel?page_size=256&target_id=1
https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel?page_size=256

**Comment by DIXX-qqfr** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Mishasama** [comment]
> 挺迷的，我这边没法复现问题 直接复制这两个网址到浏览器地址栏打开最前面是否有code 510001？（不要直接点开会报错 https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel?page_size=256&target_id=1 https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel?page_size=256

都是 "code":0

**Comment by indefined** [comment]
不好意思忘了什么时候改的接口，看上去是旧接口挂了，code 0说明这个APP新接口能用，我待会更新上去

**Comment by DIXX-qqfr** [comment]
现在似乎只能显示一个勋章，别的勋章显示不出来，关闭其他脚本也是如此

**Comment by indefined** [comment]
还会有这种问题的吗……上面那两个链接打开之后长度有什么区别吗？

**Comment by DIXX-qqfr** [comment]
但似乎0.5.46.1版本可以正常使用

**Comment by DIXX-qqfr** [comment]
{"code":0,"message":"0","ttl":1,"data":{"list":[],"special_list":[{"medal":{"uid":107867952,"target_id":3379951,"target_name":"","medal_id":23039,"level":8,"medal_name":"勋章","medal_color":6126494,"intimacy":300,"next_intimacy":1700,"day_limit":1500,"today_feed":100,"medal_color_start":6126494,"medal_color_end":6126494,"medal_color_border":6126494,"is_lighted":1,"guard_level":0,"wearing_status":0,"medal_icon_id":0,"medal_icon_url":""},"anchor_info":{"nick_name":"ilem","avatar":"http://i1.hdslb.com/bfs/face/2e25812e0ba75174c07fe9b61e68e20c66e89499.jpg","verify":0},"superscript":{"type":2,"content":"最近获得"},"room_info":{"room_id":544610,"living_status":0,"url":"https://live.bilibili.com/544610?accept_quality=%5B10000%5D\u0026broadcast_type=0\u0026current_qn=10000\u0026current_quality=10000\u0026is_room_feed=1\u0026live_from=28008\u0026live_play_network=other\u0026p2p_type=0\u0026playurl_h264=https%3A%2F%2Fd1--cn-gotcha04.bilivideo.com%2Flive-bvc%2F493377%2Flive_3379951_1473915.flv%3Fexpires%3D1641117373%26len%3D0%26oi%3D2008294127%26pt%3D%26qn%3D0%26trid%3D100018a176011d9249f89e7529ce1948270d%26sigparams%3Dcdn%2Cexpires%2Clen%2Coi%2Cpt%2Cqn%2Ctrid%26cdn%3Dcn-gotcha04%26sign%3Db9495463a18841a8c9f35c21dfd9ed43%26sk%3D2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44%26p2p_type%3D0%26src%3D8%26sl%3D1%26flowtype%3D0%26source%3Dbatch%26order%3D1%26machinezone%3Dylf%26slot%3D1\u0026playurl_h265=\u0026quality_description=%5B%7B%22qn%22%3A10000%2C%22desc%22%3A%22%E5%8E%9F%E7%94%BB%22%7D%5D"}}],"bottom_bar":null,"page_info":{"number":0,"current_page":0,"has_more":false,"next_page":2,"next_light_status":2},"total_number":16,"has_medal":0}}



{"code":0,"message":"0","ttl":1,"data":{"list":[],"special_list":[{"medal":{"uid":107867952,"target_id":3379951,"target_name":"","medal_id":23039,"level":8,"medal_name":"勋章","medal_color":6126494,"intimacy":300,"next_intimacy":1700,"day_limit":1500,"today_feed":100,"medal_color_start":6126494,"medal_color_end":6126494,"medal_color_border":6126494,"is_lighted":1,"guard_level":0,"wearing_status":0,"medal_icon_id":0,"medal_icon_url":""},"anchor_info":{"nick_name":"ilem","avatar":"http://i1.hdslb.com/bfs/face/2e25812e0ba75174c07fe9b61e68e20c66e89499.jpg","verify":0},"superscript":{"type":2,"content":"最近获得"},"room_info":{"room_id":544610,"living_status":0,"url":"https://live.bilibili.com/544610?accept_quality=%5B10000%5D\u0026broadcast_type=0\u0026current_qn=10000\u0026current_quality=10000\u0026is_room_feed=1\u0026live_from=28008\u0026live_play_network=other\u0026p2p_type=0\u0026playurl_h264=https%3A%2F%2Fd1--cn-gotcha04.bilivideo.com%2Flive-bvc%2F900478%2Flive_3379951_1473915.flv%3Fexpires%3D1641117382%26len%3D0%26oi%3D2008294127%26pt%3D%26qn%3D0%26trid%3D10007a08cdb4112e4f80a11d1763e50ad238%26sigparams%3Dcdn%2Cexpires%2Clen%2Coi%2Cpt%2Cqn%2Ctrid%26cdn%3Dcn-gotcha04%26sign%3Db8f6af9bf0756e2746bf9bbe8755b371%26sk%3D2935686d6cb9146c7a6a6a0b4e120e250342be3df4dc8310261aab0ce9e21e44%26p2p_type%3D0%26src%3D8%26sl%3D1%26flowtype%3D0%26source%3Dbatch%26order%3D1%26machinezone%3Dylf%26slot%3D1\u0026playurl_h265=\u0026quality_description=%5B%7B%22qn%22%3A10000%2C%22desc%22%3A%22%E5%8E%9F%E7%94%BB%22%7D%5D"}}],"bottom_bar":null,"page_info":{"number":0,"current_page":0,"has_more":false,"next_page":2,"next_light_status":2},"total_number":16,"has_medal":0}}
感觉没有什么区别

**Comment by indefined** [comment]
迷惑，没搞懂。0.5.46.1那个接口缺房间号，B站的接口一大堆却各有差异各种奇怪的兼容性问题。你试一下把
https://api.live.bilibili.com/xlive/app-ucenter/v1/fansMedal/panel?page_size=256&target_id=1
最后面的1改成你的B站ID试试，不用贴结果出来只要内容比前面两个长就可以了。不行的话……我只能去折腾一下别的接口试试了

**Comment by DIXX-qqfr** [comment]
这行在哪，我查找没找到

**Comment by indefined** [comment]
https://space.bilibili.com/
打开之后网址后面有个数字那个就是你的B站ID，把上面那个网站最后面的=1换成=你的B站ID试试，我也只是猜的，Bilibili-Evolved那边似乎用的同样的接口但是没看到有人报错

**Comment by indefined** [comment]
我直接推送个更新把用户ID加上去吧，也不知道有没有用，没有作用的话反馈一下我再查

**Comment by Mishasama** [comment]
> 我直接推送个更新把用户ID加上去吧，也不知道有没有用，没有作用的话反馈一下我再查

没用，还是只能获取当前佩戴和列表中的其中一个，合共两个而已。

**Comment by DIXX-qqfr** [comment]
我改成自己的ID，但长度似乎没变

**Comment by indefined** [comment]
嗯……我找找别的接口吧

**Comment by indefined** [comment]
换了网页端接口，虽然加载方式和之前一样但是体验会差很多，因为一页只有10个如果勋章多要加载很多次

**Comment by Mishasama** [comment]
> 

在网络条件好的情况还好，都是几秒内的事……而且还能缩短初始化的时间不是么😂

**Comment by Tinpa** [comment]
> 嗯……我找找别的接口吧

或许可以参考一下这个： 
https://github.com/andywang425/BLTH/pull/203/commits/5948ba93d34a9eabfd6a468984ce24b0efb33e87
看看有没有帮助？

**Comment by indefined** [comment]
昨天应该已经更新换了接口了，现在0.5.47.3还是不能用吗

**Comment by Mishasama** [comment]
> 昨天应该已经更新换了接口了，现在0.5.47.3还是不能用吗

目前除了你说的需要分次加载的问题之外暂时能用。没关issue主要是想看看有没有人看到能提供更完美的解决方案……
如果觉得没必要那就关了吧。

**Comment by indefined** [comment]
我主要看看有没有别人反馈BUG，因为每次改总会有我遇不到的问题，我自己现在基本很少用。昨天找了一番应该没别的方案了，上面那个的接口也一样是网页端的。没有问题的话我过些日子再关吧

**Comment by DIXX-qqfr** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
