### ISSUE TITLE
[bilibili网页端添加APP首页推荐] 「不感兴趣」功能的交互逻辑问题

### ISSUE THREAD

**Issue by huaxianyan** [indefined/UserScripts#94]
1. 脚本名称：

bilibili网页端添加APP首页推荐 0.6.22

2. 脚本使用环境：

Win 10 Chromium 86.0 Tampermonkey 4.14 2160x1440 125% 缩放

3. 问题详细描述：

我经常会碰到我打算滑到某一个视频同时点击打开，但是因为滑动的过程中路过了「不感兴趣」那个 X 就变成了选择一个理由提交了不感兴趣，虽然可以立刻再撤销回来，但是时间长了误操作次数还挺多的，作者看看这块的交互逻辑是否能够优化一下？

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
大概得等下次大型重构这个脚本的时候再考虑吧。最初设计的时候没想出比较靠谱的方案所以就这么用了，目前没有动这个脚本的打算，太乱了，如果有更新新版的话会一起做，否则能用的话近期不会去改它
