### ISSUE TITLE
[网易CC直播净化] 去除粉丝勋章功能失效

### ISSUE THREAD

**Issue by suheandzl** [indefined/UserScripts#95]
1. 脚本名称：

网易CC直播净化
2. 脚本使用环境：

win10 chrome 98.0.4758.102 x64 Tampermonkey BETA 4.14.6152 3840x2160 175%dpi
3. 问题详细描述：

去除粉丝勋章功能失效

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
准确来说整个聊天区域的屏蔽都失效了。粉丝勋章现在应该修复了，但新的感谢礼物和欢迎消息没法完全屏蔽

**Comment by suheandzl** [comment]
> 

感谢修复
