### ISSUE TITLE
[Hentaiverse汉化] 是否翻译 HV Utils？

### ISSUE THREAD

**Issue by lazureice** [indefined/UserScripts#96]
1. 脚本名称：Hentaiverse汉化

2. 脚本使用环境：Windows Chrome100.0

3. 问题详细描述：已经将HV Utils移动到了前面，但还是没有翻译。如果始终都不翻译，那么我就认为本来就不支持。但奇怪的是，竟翻译了一次。让我怀疑本来是支持的，是我哪里弄错了。

翻译只有一次，后面怎么刷新都不翻译：

![image](https://user-images.githubusercontent.com/12579737/163723347-8d87da60-3236-4bee-bc61-df15c56c4924.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

无错误
</code>
</pre>
</details>

**Comment by indefined** [comment]
当前版本这个菜单应该是完全不会翻译的。Monsterbation设置那个选项是原本加在原生的菜单下面的HVUT搬过去时就会顺带把原生菜单的翻译的给搬过去。HVUT的内容很多，而且很多是动态加载的，这个脚本当前的执行逻辑基本只能翻译静态内容所以大部分HVUT的内容没办法翻译，比如这个菜单是只有在你鼠标指上去的时候才会生成的所以没法提前翻译。有部分内容像是法分之类的内容原理上是可以翻译的，但考虑到一些翻译一些不翻译也挺乱的干脆就全都没翻译了

**Comment by lazureice** [comment]
好吧……
但我真的遇到过一次全部翻译的情况。
应该不是我眼花。鼠标移到顶端难度的位置，显示的都是中文，我记得很清楚是彩虹小马而不是PFUDOR。
