### ISSUE TITLE
[bilibili直播间助手] 深色模式适配

### ISSUE THREAD

**Issue by Mishasama** [indefined/UserScripts#97]
1. 脚本名称：[bilibili直播间助手](https://github.com/indefined/UserScripts/blob/master/bilibiliLive)

2. 脚本使用环境：WIN10 Firefox100.0 Tampermonkey4.17.6161

3. 问题详细描述：如图，亮瞎了……以前一直用Chrome Flag里的强制深色就没发现有这个毛病，到FF里没这个一下子就亮瞎了👁

![image](https://user-images.githubusercontent.com/54498172/168341064-2d0ef6c0-38e2-464d-a7d5-404e0f7cd3c0.png)

<details>
<summary>错误报告</summary>
<pre>
<code>

</code>
</pre>
</details>

**Comment by indefined** [comment]
不会调色，只能随便找个颜色上去了

**Comment by Mishasama** [comment]
另外还有这个问题……
![image](https://user-images.githubusercontent.com/54498172/168442104-2271bd89-4c42-42a0-88ea-a9fc7570eac0.png)
我只会美术，反色的条件JS还是你来吧😂
