### ISSUE TITLE
[bilibili直播间工具]脚本不能正常运行

### ISSUE THREAD

**Issue by shinji-ikari** [indefined/UserScripts#99]
感谢大大的脚本,真的贼好用好么,尤其是勋章确认主播有没有在播这个,想找一堆关注里面有粉丝勋章的主播确认情况贼好用了....
今天里币更新了直播间的小心心获取规则,大概是顺便更新了一些东西如接口什么的,反正脚本能看到tampermonkey有加载,但是界面跟没有运行脚本一样,同时在用的其它脚本也出现了没有运行一样的情况.

1. 脚本名称：

bilibili直播间工具

2. 脚本使用环境：

WIN7 CHROME自动更新到最新的稳定版, tampermonkey.

3. 问题详细描述：

大概是这两天提到的小心心更改获取规则,然后今天刷新了一下发现脚本运行跟没运行一样.

<details>
<summary>错误报告</summary>
<pre>
<code>

Bilibili Live V4.0.0 "Life Experience" Lovingly By © 2014 - 2022 Bilibili Live Department  ...(●'◡'●)ﾉ♥   # Renascence #
179.4d4cef7cd25db7e00db6.js:2 Version: V4.0.0 "Life Experience", CodeName: Neptune.
sentry-5.2.1.min.js:2 medal t Array(10)
DevTools failed to load source map: Could not load content for https://activity.hdslb.com/CommonFilter.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/room-player.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/room-player.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
</code>
</pre>
</details>

**Comment by indefined** [comment]
没有发现有运行问题，确认是可以复现的问题吗？直播间界面有没有明显更改的地方？B站有些更新是灰度部分推送的，如果确实是更新了的话可能是我这边没收到，得等我能复现问题才能修

**Comment by shinji-ikari** [comment]
hmmm.那有点奇怪了.目前脚本还是运行不起来.我应该怎么做去确认哪里有问题?我这边只能确认昨天还正常.并且没有做什么修改或者调整的增删插件什么的动作.今天刷新之后发现tampermonkey有加载脚本,但是界面上没有任何的脚本正常运行的情况.
(⇀‸↼‶)....我把chrome删了重新装,先测试的脚本.目前正常.这是真让我想不到了
